Faeterna::Scripts::Enemigos::Enemy
int Faeterna.Scripts.Enemigos.Enemy.health
Puntos de vida actuales del enemigo. Se asigna desde el editor.
Referenced by Faeterna.Scripts.Enemigos.Slime.Slime._PhysicsProcess.
float Faeterna.Scripts.Enemigos.Enemy.dashSpeed
Velocidad de desplazamiento durante el dash del enemigo (px/s). Se asigna desde el editor.
Referenced by Faeterna.scripts.Enemigos.Jabali.Jabali._PhysicsProcess.
float Faeterna.Scripts.Enemigos.Enemy.jumpVelocity
Velocidad vertical aplicada al iniciar un salto (negativa = hacia arriba). Se asigna desde el editor.
AnimatedSprite2D Faeterna.Scripts.Enemigos.Enemy.animatedSprite
Referencia al nodo AnimatedSprite2D que renderiza las animaciones del enemigo. Se asigna desde el editor.
Referenced by Faeterna.Scripts.Enemigos.Enemy._Ready, Faeterna.scripts.Enemigos.Jabali.Jabali._Ready, Faeterna.Scripts.Enemigos.Slime.Slime._Ready, Faeterna.Scripts.Enemigos.Enemy.SetAnimation.
float Faeterna.Scripts.Enemigos.Enemy.dashDuration
Duración del dash del enemigo en segundos. Se asigna desde el editor.
float Faeterna.Scripts.Enemigos.Enemy.knockbackDuration
Duración del knockback aplicado al enemigo en segundos. Se asigna desde el editor.
bool Faeterna.Scripts.Enemigos.Enemy.flipSprite
Booleano que controla si el sprite del enemigo debe estar invertido (mirada izquierda/derecha). Se asigna desde el editor.
Referenced by Faeterna.Scripts.Enemigos.Slime.Slime._EnterTree.
AudioStreamPlayer2D Faeterna.Scripts.Enemigos.Enemy.audioPlayer
Reproductor de audio para los efectos de sonido del enemigo. Se asigna desde el editor.
Referenced by Faeterna.Scripts.Enemigos.Enemy.playAudio.
CollisionShape2D Faeterna.Scripts.Enemigos.Enemy.detectionArea
Área de detección del enemigo utilizada para detectar al jugador. Se asigna desde el editor.
RayCast2D Faeterna.Scripts.Enemigos.Enemy.groundCheck
RayCast2D que verifica si el enemigo está en el suelo. Se asigna desde el editor.
Referenced by Faeterna.scripts.Enemigos.Jabali.Jabali._PhysicsProcess.
Area2D Faeterna.Scripts.Enemigos.Enemy.hurtBox
Área de daño del enemigo que causa daño al jugador al colisionar. Se asigna desde el editor.
Area2D Faeterna.Scripts.Enemigos.Enemy.attackHitBox
Área de ataque del enemigo que inflige daño cuando golpea. Se asigna desde el editor.
int Faeterna.Scripts.Enemigos.Enemy.dashDirection
Dirección del dash del enemigo (1 = derecha, -1 = izquierda).
float Faeterna.Scripts.Enemigos.Enemy.knockbackTimer
Temporizador para controlar la duración del knockback aplicado al enemigo.
Referenced by Faeterna.Scripts.Enemigos.Slime.Slime._PhysicsProcess.
ShaderMaterial Faeterna.Scripts.Enemigos.Enemy.shaderMaterial
Material de shader utilizado para efectos visuales de daño (como destello blanco).
Referenced by Faeterna.Scripts.Enemigos.Slime.Slime._Ready.
Node2D Faeterna.Scripts.Enemigos.Enemy.target
Referencia al objetivo actual del enemigo (generalmente el jugador). Es null si no hay objetivo.
Referenced by Faeterna.Scripts.Enemigos.Slime.Slime._on_detection_area_body_entered, Faeterna.Scripts.Enemigos.Slime.Slime._on_detection_area_body_exited, Faeterna.scripts.Enemigos.Jabali.Jabali._PhysicsProcess.
float Faeterna.Scripts.Enemigos.Enemy.Gravity
Gravedad obtenida del ProjectSettings, utilizada para la física del enemigo.
Referenced by Faeterna.scripts.Enemigos.Jabali.Jabali._PhysicsProcess, Faeterna.Scripts.Enemigos.Slime.Slime._PhysicsProcess.
override void Faeterna.Scripts.Enemigos.Enemy._Ready()
Inicialización del nodo.
Obtiene la referencia al AnimatedSprite2D hijo si no está asignado.
References Faeterna.Scripts.Enemigos.Enemy.animatedSprite.
async void Faeterna.Scripts.Enemigos.Enemy.hitShader(ShaderMaterial shader)
Aplica un efecto de shader de destello blanco al enemigo cuando recibe daño.
El efecto dura 0.1 segundos (100 ms) y luego vuelve al estado normal. shader Material de shader al cual se le aplicará el efecto de destello.
void Faeterna.Scripts.Enemigos.Enemy.playAudio(AudioStream audio)
Reproduce un efecto de sonido del enemigo a través del reproductor de audio.
audio AudioStream que contiene el sonido a reproducir.
References Faeterna.Scripts.Enemigos.Enemy.audioPlayer.
Referenced by Faeterna.scripts.Enemigos.Jabali.Jabali._PhysicsProcess.
void Faeterna.Scripts.Enemigos.Enemy.SetAnimation(string animationName)
Reproduce una animación en el sprite del enemigo.
animationName Nombre de la animación a reproducir.
References Faeterna.Scripts.Enemigos.Enemy.animatedSprite.
Referenced by Faeterna.scripts.Enemigos.Jabali.Jabali._on_detection_area_body_entered, Faeterna.scripts.Enemigos.Jabali.Jabali._PhysicsProcess, Faeterna.Scripts.Enemigos.Slime.Slime._PhysicsProcess, Faeterna.scripts.Enemigos.Jabali.Jabali._Ready, Faeterna.Scripts.Enemigos.Slime.Slime._Ready.