Faeterna::scripts::Enemigos::ReyJabali::ReyJabali
ShaderMaterial Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._shaderMaterial
Material del shader usado para el efecto visual de daño.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._Ready, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.TakeDamage.
bool Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isDashing
Indica si el boss está actualmente dashing.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_boss_area_body_entered, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_boss_area_body_exited, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_dash_timer_timeout, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_load_attack_timer_timeout, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._PhysicsProcess, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.moveToinitPosition, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.TakeDamage.
bool Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isChargingAttack
Indica si el boss está cargando un ataque.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_boss_area_body_entered, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_boss_area_body_exited, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_dash_timer_timeout, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_load_attack_timer_timeout, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._PhysicsProcess, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.moveToinitPosition, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.TakeDamage.
bool Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isDead
Indica si el boss ya murió.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_load_attack_timer_timeout, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._PhysicsProcess, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.moveToinitPosition, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.OnHurtBoxAreaEntered, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.TakeDamage.
bool Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._jumped
Estado auxiliar para detectar si el boss venía subiendo en el salto.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._PhysicsProcess.
bool Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._falled
Estado auxiliar para detectar si el boss ya entró en fase de caída.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._PhysicsProcess.
int Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._dashCount
Número de dashes realizados antes de entrar en la fase de salto especial.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_load_attack_timer_timeout, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.DoNextJump.
int Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._jumpCount
Número de saltos ejecutados dentro de la secuencia especial.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_load_attack_timer_timeout, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.DoNextJump.
int Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._actionsBeforeJump
Cantidad de acciones antes de pasar al salto especial.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_load_attack_timer_timeout, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.DoNextJump.
bool Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isReturningHome
Indica si el boss está volviendo a su posición inicial.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_boss_area_body_entered, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_boss_area_body_exited, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._PhysicsProcess.
float Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._arrivalThreshold
Distancia mínima para considerar que el boss llegó a casa.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._PhysicsProcess.
int Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._currentDirection
Dirección horizontal actual del boss.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_boss_area_body_entered, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_dash_timer_timeout, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_load_attack_timer_timeout, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._PhysicsProcess, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._Ready, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.DoNextJump, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.FlipHJabali, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.moveToinitPosition, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.OnHurtBoxAreaEntered.
Vector2 Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._initPosition
Posición inicial usada para volver a casa cuando el jugador se aleja.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._EnterTree, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.moveToinitPosition.
bool Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._startFacingLeft
Indica si el boss empieza mirando hacia la izquierda.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._PhysicsProcess, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._Ready, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.moveToinitPosition.
Area2D Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._bossArea
Área de detección del jugador.
Area2D Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._attackHitBox
Área de ataque del boss.
Area2D Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._hurtBox
Área que recibe daño.
Timer Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._dashTimer
Timer que controla la duración del dash.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_load_attack_timer_timeout, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._PhysicsProcess.
Timer Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._loadAttackTimer
Timer que controla la carga del ataque.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_boss_area_body_entered, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_boss_area_body_exited, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_dash_timer_timeout, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_load_attack_timer_timeout, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.TakeDamage.
Timer Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._deathAnimationTimer
Timer que espera a que termine la animación de muerte.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.TakeDamage.
AudioStream Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._jumpAudio
Sonido del salto.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._PhysicsProcess.
AudioStream Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._hitAudio
Sonido de daño recibido.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.TakeDamage.
AudioStream Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._runAudio
Sonido de carrera.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_load_attack_timer_timeout.
Random Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._rnd
Generador aleatorio usado para variar la secuencia de ataques.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_load_attack_timer_timeout, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.DoNextJump.
float Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.WalkSpeed
Velocidad de caminata normal del boss.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._PhysicsProcess.
delegate void Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.jabaliBossdeathEventHandler()
Señal emitida cuando el boss muere.
override void Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._EnterTree()
Captura la posición inicial al entrar en el árbol de escenas.
References Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._initPosition.
override void Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._Ready()
Inicializa la dirección del boss, prepara el shader y fija la animación inicial.
References Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._currentDirection, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._shaderMaterial, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._startFacingLeft, Faeterna.Scripts.Enemigos.Enemy.animatedSprite, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.FlipHJabali, Faeterna.Scripts.Enemigos.Enemy.SetAnimation.
override void Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._PhysicsProcess(double delta)
Control principal de física del boss: gravedad, persecución, regreso a casa y knockback.
delta Tiempo transcurrido desde el último frame.
References Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._arrivalThreshold, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._currentDirection, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._dashTimer, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._falled, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isChargingAttack, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isDashing, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isDead, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isReturningHome, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._jumpAudio, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._jumped, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._startFacingLeft, Faeterna.Scripts.Enemigos.Enemy.dashSpeed, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.FlipHJabali, Faeterna.Scripts.Enemigos.Enemy.Gravity, Faeterna.Scripts.Enemigos.Enemy.playAudio, Faeterna.Scripts.Enemigos.Enemy.SetAnimation, Faeterna.Scripts.Enemigos.Enemy.target, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.WalkSpeed.
void Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_load_attack_timer_timeout()
Se llama cuando termina el tiempo de carga del ataque y decide si el boss corre o salta.
References Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._actionsBeforeJump, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._currentDirection, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._dashCount, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._dashTimer, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isChargingAttack, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isDashing, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isDead, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._jumpCount, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._loadAttackTimer, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._rnd, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._runAudio, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.DoNextJump, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.FlipHJabali, Faeterna.Scripts.Enemigos.Enemy.playAudio, Faeterna.Scripts.Enemigos.Enemy.target.
void Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_dash_timer_timeout()
Finaliza la fase de dash y prepara la siguiente carga del ataque.
References Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._currentDirection, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isChargingAttack, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isDashing, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._loadAttackTimer, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.FlipHJabali, Faeterna.Scripts.Enemigos.Enemy.target.
void Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_attack_hit_box_body_entered(Node2D prota)
Aplica daño al jugador cuando entra en el hitbox de ataque del boss.
prota Nodo que entró en el hitbox.
void Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_boss_area_body_entered(Node2D prota)
Detecta la entrada del jugador en el área del boss y activa el combate.
prota Cuerpo que entró en el área del boss.
References Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._currentDirection, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isChargingAttack, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isDashing, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isReturningHome, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._loadAttackTimer, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.FlipHJabali, Faeterna.Scripts.Enemigos.Enemy.target.
void Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_boss_area_body_exited(Node2D prota)
Detecta la salida del jugador y prepara el regreso del boss a su posición inicial.
prota Cuerpo que salió del área del boss.
References Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isChargingAttack, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isDashing, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isReturningHome, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._loadAttackTimer, Faeterna.Scripts.Enemigos.Enemy.target.
Vector2 Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.DoNextJump()
Calcula el siguiente salto de la secuencia especial del boss.
Vector de velocidad a aplicar al boss.
References Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._actionsBeforeJump, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._currentDirection, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._dashCount, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._jumpCount, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._rnd, Faeterna.Scripts.Enemigos.Enemy.dashSpeed, Faeterna.Scripts.Enemigos.Enemy.jumpVelocity.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_load_attack_timer_timeout.
void Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.FlipHJabali()
Voltea el sprite del boss y actualiza su dirección horizontal.
References Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._currentDirection.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_boss_area_body_entered, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_dash_timer_timeout, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._on_load_attack_timer_timeout, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._PhysicsProcess, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._Ready, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.moveToinitPosition, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.OnHurtBoxAreaEntered.
void Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.OnHurtBoxAreaEntered(Area2D area)
Procesa el daño recibido por el boss desde su hurtbox.
area Área que colisionó con el boss.
References Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._currentDirection, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isDead, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.FlipHJabali, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.TakeDamage, Faeterna.Scripts.Enemigos.Enemy.target.
void Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.TakeDamage(int amount, Vector2 sourcePosition)
Aplica daño al boss y controla la transición a muerte o al knockback.
amount Cantidad de daño recibida. sourcePosition Posición del atacante para calcular la dirección del knockback.
References Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._deathAnimationTimer, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._hitAudio, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isChargingAttack, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isDashing, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isDead, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._loadAttackTimer, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._shaderMaterial, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.DesactiveCollision, Faeterna.Scripts.Enemigos.Enemy.health, Faeterna.Scripts.Enemigos.Enemy.hitShader, Faeterna.Scripts.Tools.GameSaveService.MarkBossDefeated, Faeterna.Scripts.Enemigos.Enemy.playAudio, Faeterna.Scripts.Enemigos.Enemy.SetAnimation.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.OnHurtBoxAreaEntered.
void Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.OnDeathAnimationTimerTimeout()
Elimina el nodo del boss cuando termina la animación de muerte.
void Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.DesactiveCollision()
Desactiva las colisiones del boss para que no interactúe tras morir.
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.TakeDamage.
void Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.moveToinitPosition()
Devuelve al boss a su posición inicial si el jugador se aleja.
References Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._currentDirection, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._initPosition, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isChargingAttack, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isDashing, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._isDead, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali._startFacingLeft, Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.FlipHJabali, Faeterna.Scripts.Enemigos.Enemy.SetAnimation, Faeterna.Scripts.Enemigos.Enemy.target.