Faeterna::Scripts::Tools::Saves
const string Faeterna.Scripts.Tools.Saves.PreviewDirectory
Directorio donde se almacenan las imágenes de vista previa de las partidas guardadas.
Referenced by Faeterna.Scripts.Tools.Saves.EnsurePreviewDirectory.
const int Faeterna.Scripts.Tools.Saves.PreviewWidth
Ancho (en píxeles) de las imágenes de vista previa generadas de las partidas.
Referenced by Faeterna.Scripts.Tools.Saves.SavePreview.
const int Faeterna.Scripts.Tools.Saves.PreviewHeight
Alto (en píxeles) de las imágenes de vista previa generadas de las partidas.
Referenced by Faeterna.Scripts.Tools.Saves.SavePreview.
readonly JsonSerializerOptions Faeterna.Scripts.Tools.Saves.JsonOptions
Opciones de formato JSON para la serialización de datos de partida (indentado para legibilidad).
Referenced by Faeterna.Scripts.Tools.Saves.LoadAsync, Faeterna.Scripts.Tools.Saves.SaveAsync.
readonly ConfigFile Faeterna.Scripts.Tools.Saves.config
Archivo de configuración usado para almacenar opciones de usuario (audio, video, etc.).
Referenced by Faeterna.Scripts.Tools.Saves.Load, Faeterna.Scripts.Tools.Saves.LoadOptions, Faeterna.Scripts.Tools.Saves.SaveOptions.
int Faeterna.Scripts.Tools.Saves.ActiveSlot
Slot activo global para las operaciones de guardado/carga de partida.
Este valor determina en qué espacio se guardará o cargará la partida.
Referenced by Faeterna.Scripts.Tools.Saves.HasSaveInActiveSlot, Faeterna.Scripts.Tools.Saves.LoadActiveSlotAsync, Faeterna.Scripts.Tools.Saves.SaveCheckpointAsync, Faeterna.Scripts.Tools.Saves.SetActiveSlot.
Faeterna.Scripts.Tools.Saves.Saves(bool isSave)
Constructor que inicializa el gestor de guardado.
Si isSave es verdadero, se prepara para guardar; si es falso, se carga el archivo de configuración desde el almacenamiento persistente. isSave Indica si se inicializa para guardar (verdadero) o para cargar opciones (falso).
References Faeterna.Scripts.Tools.Saves.Load.
void Faeterna.Scripts.Tools.Saves.Load(string filename)
Carga el archivo de configuración desde la ruta especificada.
Si el archivo no existe, crea uno nuevo. filename Ruta del archivo de configuración a cargar.
References Faeterna.Scripts.Tools.Saves.config.
Referenced by Faeterna.Scripts.Tools.Saves.Saves.
void Faeterna.Scripts.Tools.Saves.SaveOptions(int antialiasing, int vsync, int screen, int fpslock, int fpsValue, int shadows, double master, double music, double soundfx, double enviroment, double uisound)
Guarda las opciones de usuario (video y audio) en el archivo de configuración persistente.
antialiasing Opción de antialiasing seleccionada (0-5: Off, FXAA, TAA, MSAA 2x, MSAA 4x, MSAA 8x). vsync Opción de VSync (0: Off, 1: On). screen Modo de pantalla (0: Ventana, 1: Pantalla completa, 2: Sin bordes). fpslock Bloqueo de FPS (0: Off, 1: On). fpsValue Límite de FPS cuando el bloqueo está activado. shadows Nivel de calidad de sombras (0-5: Hard, Soft Very Low, Soft Low, Soft Medium, Soft High, Soft Ultra). master Volumen maestro (0.0-1.0). music Volumen de música (0.0-1.0). soundfx Volumen de efectos de sonido (0.0-1.0). enviroment Volumen de sonidos ambientales (0.0-1.0). uisound Volumen de sonidos de UI (0.0-1.0).
References Faeterna.Scripts.Tools.Saves.config.
OptionsData Faeterna.Scripts.Tools.Saves.LoadOptions()
Carga las opciones de usuario guardadas y las devuelve como un registro OptionsData.
Si alguna opción no está guardada, se usan valores predeterminados. Registro con las opciones cargadas del archivo de configuración.
References Faeterna.Scripts.Tools.Saves.config, Faeterna.Scripts.Tools.OptionsData.
static void Faeterna.Scripts.Tools.Saves.SetActiveSlot(int slot)
Define el slot activo asegurando que no sea negativo.
Un valor negativo se reemplaza automáticamente con 0. slot Índice del slot a activar (base 0).
References Faeterna.Scripts.Tools.Saves.ActiveSlot.
static bool Faeterna.Scripts.Tools.Saves.HasSave(int slot)
Verifica si existe un archivo de guardado para el slot especificado.
slot Índice del slot a verificar (base 0). Verdadero si existe el archivo JSON del slot; falso en caso contrario.
References Faeterna.Scripts.Tools.Saves.GetSlotPath.
Referenced by Faeterna.Scripts.Tools.Saves.HasSaveInActiveSlot.
static bool Faeterna.Scripts.Tools.Saves.HasSaveInActiveSlot()
Verifica si el slot activo tiene un archivo de guardado.
Verdadero si existe guardado en el slot activo; falso en caso contrario.
References Faeterna.Scripts.Tools.Saves.ActiveSlot, Faeterna.Scripts.Tools.Saves.HasSave.
static bool Faeterna.Scripts.Tools.Saves.HasPreview(int slot)
Verifica si existe una imagen de vista previa para el slot especificado.
slot Índice del slot a verificar (base 0). Verdadero si existe la imagen PNG del slot; falso en caso contrario.
References Faeterna.Scripts.Tools.Saves.GetSlotPreviewPath.
Referenced by Faeterna.Scripts.Tools.Saves.LoadPreviewTexture.
static Texture2D Faeterna.Scripts.Tools.Saves.LoadPreviewTexture(int slot)
Carga la textura de vista previa del slot desde el almacenamiento persistente.
slot Índice del slot de cuya previsualizacion se cargará (base 0). Una Texture2D lista para usar en UI, o nulo si no existe o está corrupta.
References Faeterna.Scripts.Tools.Saves.GetSlotPreviewPath, Faeterna.Scripts.Tools.Saves.HasPreview.
static void Faeterna.Scripts.Tools.Saves.DeleteSlot(int slot)
Elimina completamente un slot incluyendo su archivo de guardado JSON y su imagen de vista previa PNG.
slot Índice del slot a eliminar (base 0).
References Faeterna.Scripts.Tools.Saves.DeleteFileIfExists, Faeterna.Scripts.Tools.Saves.GetSlotPath, Faeterna.Scripts.Tools.Saves.GetSlotPreviewPath.
static async Task Faeterna.Scripts.Tools.Saves.SaveCheckpointAsync(Lira player, string checkpointId, string scenePath, Vector2 checkpointPosition, Viewport viewport=null)
Guarda el progreso de un checkpoint y genera una imagen de vista previa del estado actual del juego.
player Instancia del jugador desde la que se extrae el estado para guardar. checkpointId Identificador único del checkpoint alcanzado. scenePath Ruta de la escena actual para validar cargas posteriores. checkpointPosition Posición de respawn a persistir cuando se cargue desde este checkpoint. viewport Viewport fuente para la captura de pantalla; si es nulo, usa el del jugador. Tarea asincrónica que completa cuando se guardan los datos y la previsualizacion.
References Faeterna.Scripts.Tools.Saves.ActiveSlot, Faeterna.Scripts.Personaje.Lira.BuildSaveData, Faeterna.Scripts.Tools.GameSaveService.GetDefeatedBossList, Faeterna.Scripts.Tools.Saves.GetSlotPreviewPath, Faeterna.Scripts.Tools.Saves.SaveAsync, Faeterna.Scripts.Tools.Saves.SavePreview.
static Task< GameData > Faeterna.Scripts.Tools.Saves.LoadActiveSlotAsync()
Carga los datos de la partida guardada en el slot activo.
Datos cargados desde el slot activo, o nulo si el archivo no existe.
References Faeterna.Scripts.Tools.Saves.ActiveSlot, Faeterna.Scripts.Tools.Saves.LoadAsync.
Referenced by Faeterna.Scripts.Tools.GameSaveService.LoadActiveSlotAsync.
static async Task Faeterna.Scripts.Tools.Saves.SaveAsync(int slot, GameData data)
Guarda los datos de una partida en el slot especificado usando el sistema de archivo persistente.
Los datos se serializan como JSON indentado para legibilidad. slot Índice del slot en el que se guardarán los datos (base 0). data Datos serializables de la partida a guardar. Tarea asincrónica que completa cuando se escriben los datos en disco.
References Faeterna.Scripts.Tools.Saves.GetSlotPath, Faeterna.Scripts.Tools.Saves.JsonOptions.
Referenced by Faeterna.Scripts.Tools.Saves.SaveCheckpointAsync.
static async Task< GameData > Faeterna.Scripts.Tools.Saves.LoadAsync(int slot)
Carga los datos de una partida desde el slot especificado desde el almacenamiento persistente.
slot Índice del slot del que se cargarán los datos (base 0). Datos de la partida cargados, o nulo si el archivo del slot no existe.
References Faeterna.Scripts.Tools.Saves.GetSlotPath, Faeterna.Scripts.Tools.Saves.JsonOptions.
Referenced by Faeterna.Scripts.Tools.Saves.LoadActiveSlotAsync.
static string Faeterna.Scripts.Tools.Saves.GetSlotPath(int slot)
Genera la ruta del archivo JSON para un slot específico.
slot Índice del slot (base 0). Ruta del archivo JSON del slot.
Referenced by Faeterna.Scripts.Tools.Saves.DeleteSlot, Faeterna.Scripts.Tools.Saves.HasSave, Faeterna.Scripts.Tools.Saves.LoadAsync, Faeterna.Scripts.Tools.Saves.SaveAsync.
static string Faeterna.Scripts.Tools.Saves.GetSlotPreviewPath(int slot)
Genera la ruta del archivo PNG de vista previa para un slot específico.
slot Índice del slot (base 0). Ruta del archivo PNG de previsualizacion del slot.
Referenced by Faeterna.Scripts.Tools.Saves.DeleteSlot, Faeterna.Scripts.Tools.Saves.HasPreview, Faeterna.Scripts.Tools.Saves.LoadPreviewTexture, Faeterna.Scripts.Tools.Saves.SaveCheckpointAsync.
static void Faeterna.Scripts.Tools.Saves.SavePreview(Viewport viewport, string previewPath)
Captura una imagen del viewport especificado, la redimensiona al tamaño estándar de previsualizacion y la guarda como archivo PNG en la ruta especificada.
viewport Viewport de cuya textura se capturará la image. previewPath Ruta donde se guardará la imagen PNG.
References Faeterna.Scripts.Tools.Saves.EnsurePreviewDirectory, Faeterna.Scripts.Tools.Saves.PreviewHeight, Faeterna.Scripts.Tools.Saves.PreviewWidth.
Referenced by Faeterna.Scripts.Tools.Saves.SaveCheckpointAsync.
static void Faeterna.Scripts.Tools.Saves.EnsurePreviewDirectory()
Crea el directorio de previsualizaciones si no existe.
Necesario antes de guardar imágenes de vista previa.
References Faeterna.Scripts.Tools.Saves.PreviewDirectory.
Referenced by Faeterna.Scripts.Tools.Saves.SavePreview.
static void Faeterna.Scripts.Tools.Saves.DeleteFileIfExists(string userPath, string fileDescription)
Intenta eliminar un archivo del almacenamiento persistente.
Imprime un aviso si la eliminación falla. userPath Ruta del archivo a eliminar. fileDescription Descripción del archivo para mensajes de log (ej: "save slot 1").
Referenced by Faeterna.Scripts.Tools.Saves.DeleteSlot.