Faeterna::Scripts::Tools::ButtonTools
readonly Vector2 Faeterna.Scripts.Tools.ButtonTools.PressedScale
Escala a la que se reduce el botón cuando se presiona (enciogimiento).
Referenced by Faeterna.Scripts.Tools.ButtonTools.PlayPressAnimation.
readonly Vector2 Faeterna.Scripts.Tools.ButtonTools.BounceScale
Escala a la que rebota el botón después de presionarse (mayor que normal).
Referenced by Faeterna.Scripts.Tools.ButtonTools.PlayPressAnimation.
readonly Vector2 Faeterna.Scripts.Tools.ButtonTools.NormalScale
Escala normal del botón (sin transformar).
Referenced by Faeterna.Scripts.Tools.ButtonTools.PlayPressAnimation.
const float Faeterna.Scripts.Tools.ButtonTools.PressDuration
Duración en segundos de la fase de presión (enciogimiento) del botón.
Referenced by Faeterna.Scripts.Tools.ButtonTools.PlayPressAnimation.
const float Faeterna.Scripts.Tools.ButtonTools.BounceDuration
Duración en segundos de la fase de rebote del botón.
Referenced by Faeterna.Scripts.Tools.ButtonTools.PlayPressAnimation.
const float Faeterna.Scripts.Tools.ButtonTools.SettleDuration
Duración en segundos de la fase de asentamiento en la escala normal.
Referenced by Faeterna.Scripts.Tools.ButtonTools.PlayPressAnimation.
static void Faeterna.Scripts.Tools.ButtonTools.PlayPressAnimation(Control button, Action onFinished=null)
Reproduce una animación de "press" en el botón: se encoge, luego rebota más grande de lo normal y vuelve a su tamaño original.
Al terminar la animación ejecuta el callback onFinished si se proporciona. No requiere que el método que lo llame sea async. button Control (botón) al que se le aplicará la animación de presión. onFinished Callback opcional que se ejecutará cuando la animación termine completamente.
References Faeterna.Scripts.Tools.ButtonTools.BounceDuration, Faeterna.Scripts.Tools.ButtonTools.BounceScale, Faeterna.Scripts.Tools.ButtonTools.NormalScale, Faeterna.Scripts.Tools.ButtonTools.PressDuration, Faeterna.Scripts.Tools.ButtonTools.PressedScale, Faeterna.Scripts.Tools.ButtonTools.SettleDuration.
Referenced by Faeterna.Scripts.Menus.PauseMenu.ExitToMenu, Faeterna.Scripts.Menus.PlayMenu.OnBackPressed, Faeterna.Scripts.Menus.DeathScreen.OnContinuarPressed, Faeterna.Scripts.Menus.PlayMenu.OnDeletePressed, Faeterna.Scripts.Menus.MainMenu.OnExitPressed, Faeterna.Scripts.Menus.OptionsMenu.OnExitPressed, Faeterna.Scripts.Menus.MainMenu.OnPlayPressed, Faeterna.Scripts.Menus.DeathScreen.OnReturnPressed, Faeterna.Scripts.Menus.OptionsMenu.OnSavePressed, Faeterna.Scripts.Menus.PlayMenu.OnSavePressed, Faeterna.Scripts.Menus.MainMenu.OnSettingsPressed, Faeterna.Scripts.Menus.PauseMenu.OpenSettings, Faeterna.Scripts.Menus.PauseMenu.ResumeGame.