Faeterna::Scripts::Tools::GameSaveService
int Faeterna.Scripts.Tools.GameSaveService.ActiveSlot
GameData Faeterna.Scripts.Tools.GameSaveService.PendingGameData
Datos de juego pendientes de aplicar tras cargar/recargar una escena.
Se usan para almacenar temporalmente el GameData mientras se realiza ChangeScene y poder aplicarlo al nuevo nodo jugador cuando la escena se haya cargado.
Referenced by Faeterna.Scripts.Tools.GameSaveService.RetrieveAndClearPending, Faeterna.Scripts.Tools.GameSaveService.SetPendingGameData.
readonly System.Collections.Generic.HashSet<string> Faeterna.Scripts.Tools.GameSaveService._defeatedBosses
static void Faeterna.Scripts.Tools.GameSaveService.SetPendingGameData(GameData data)
Establece datos pendientes que serán aplicados tras completar el cambio de escena.
data GameData a aplicar después de recargar la escena.
References Faeterna.Scripts.Tools.GameSaveService.PendingGameData.
Referenced by Faeterna.Scripts.Personaje.Lira.TryLoadFromActiveSlotAsync.
static GameData Faeterna.Scripts.Tools.GameSaveService.RetrieveAndClearPending()
Recupera y limpia los datos pendientes.
GameData previamente pendiente o null.
References Faeterna.Scripts.Tools.GameSaveService.PendingGameData.
Referenced by Faeterna.Scripts.Personaje.Lira.TryLoadFromActiveSlotAsync.
static void Faeterna.Scripts.Tools.GameSaveService.MarkBossDefeated(string bossType)
Marca un boss como derrotado (persistible en el siguiente guardado).
bossType Identificador del boss (por ejemplo el nombre de la clase).
Referenced by Faeterna.scripts.Enemigos.ReyJabali.ReyJabali.TakeDamage.
static System.Collections.Generic.List< string > Faeterna.Scripts.Tools.GameSaveService.GetDefeatedBossList()
Devuelve una lista copiada de los bosses derrotados actualmente registrados.
Lista de identificadores de bosses derrotados.
Referenced by Faeterna.Scripts.Tools.Saves.SaveCheckpointAsync.
static void Faeterna.Scripts.Tools.GameSaveService.SetDefeatedBosses(System.Collections.Generic.IEnumerable< string > list)
Reemplaza la lista de bosses derrotados (usado al cargar un guardado).
Referenced by Faeterna.Scripts.Tools.GameSaveService.LoadActiveSlotAsync, Faeterna.Scripts.Personaje.Lira.TryLoadFromActiveSlotAsync.
static void Faeterna.Scripts.Tools.GameSaveService.SetActiveSlot(int slot)
Define el slot activo asegurando que no sea negativo.
slot Indice del slot (base 0).
Referenced by Faeterna.Scripts.Menus.PlayMenu.OnSavePressed.
static bool Faeterna.Scripts.Tools.GameSaveService.HasSave(int slot)
Indica si existe archivo de guardado para el slot dado.
slot Indice del slot (base 0). true si existe el JSON del slot; en caso contrario, false.
Referenced by Faeterna.Scripts.Menus.PlayMenu.RefreshSlotVisuals.
static bool Faeterna.Scripts.Tools.GameSaveService.HasSaveInActiveSlot()
Indica si el slot activo tiene archivo de guardado.
true si existe guardado en el slot activo.
static bool Faeterna.Scripts.Tools.GameSaveService.HasPreview(int slot)
Indica si existe una imagen preview asociada al slot.
slot Indice del slot (base 0). true si existe la imagen PNG del slot.
static Texture2D Faeterna.Scripts.Tools.GameSaveService.LoadPreviewTexture(int slot)
Carga la textura de preview del slot desde disco.
slot Indice del slot (base 0). Una Texture2D lista para usar en UI, o null si no existe/esta corrupta.
static void Faeterna.Scripts.Tools.GameSaveService.DeleteSlot(int slot)
Elimina el guardado completo de un slot (datos JSON + preview PNG).
slot Indice del slot (base 0).
Referenced by Faeterna.Scripts.Menus.PlayMenu.OnSavePressed.
static Task Faeterna.Scripts.Tools.GameSaveService.SaveCheckpointAsync(PlayerType player, string checkpointId, string scenePath, Vector2 checkpointPosition, Viewport viewport=null)
Guarda el progreso al tocar un checkpoint y genera la imagen preview del slot activo.
player Instancia del jugador desde la que se extrae el estado. checkpointId Identificador del checkpoint alcanzado. scenePath Ruta de escena actual para validar cargas posteriores. checkpointPosition Posicion de respawn a persistir. viewport Viewport fuente para la captura; si es null, usa el del jugador. Tarea asincrona de guardado.
Referenced by Faeterna.Scripts.Tools.CheckPoint.ActionSaveProgress.
static async Task< GameData > Faeterna.Scripts.Tools.GameSaveService.LoadActiveSlotAsync()
Carga los datos del slot activo.
Datos cargados o null si el archivo no existe.
References Faeterna.Scripts.Tools.Saves.LoadActiveSlotAsync, Faeterna.Scripts.Tools.GameSaveService.SetDefeatedBosses.
Referenced by Faeterna.Scripts.Menus.DeathScreen.ContinueFromLastSaveAsync, Faeterna.Scripts.Personaje.Lira.TryLoadFromActiveSlotAsync.
static Task Faeterna.Scripts.Tools.GameSaveService.SaveAsync(int slot, GameData data)
Guarda en disco los datos de un slot usando SaveFile<TData>.
slot Indice del slot (base 0). data Datos serializables de la partida. Tarea asincrona de escritura.
static Task< GameData > Faeterna.Scripts.Tools.GameSaveService.LoadAsync(int slot)
Carga desde disco los datos de un slot usando SaveFile<TData>.
slot Indice del slot (base 0). Datos cargados o null si el archivo del slot no existe.