Faeterna::Scripts::Menus::DeathScreen
const string Faeterna.Scripts.Menus.DeathScreen.DefaultGameScenePath
Ruta por defecto a la escena principal del juego si no existe una escena guardada válida.
Referenced by Faeterna.Scripts.Menus.DeathScreen.ContinueFromLastSaveAsync.
const float Faeterna.Scripts.Menus.DeathScreen.FadeInDuration
Duración del efecto de aparición gradual de la pantalla de muerte.
Referenced by Faeterna.Scripts.Menus.DeathScreen.ChangeVisibility.
TextureButton Faeterna.Scripts.Menus.DeathScreen._continueButton
Botón que continúa la partida cargando el último guardado.
Referenced by Faeterna.Scripts.Menus.DeathScreen._Ready, Faeterna.Scripts.Menus.DeathScreen.OnContinuarPressed.
TextureButton Faeterna.Scripts.Menus.DeathScreen._returnButton
Botón que devuelve al jugador al menú principal.
Referenced by Faeterna.Scripts.Menus.DeathScreen._Ready, Faeterna.Scripts.Menus.DeathScreen.OnReturnPressed.
override void Faeterna.Scripts.Menus.DeathScreen._Ready()
Inicializa la pantalla de muerte.
La deja oculta por defecto y configura los botones para que funcionen incluso durante la pausa del juego.
References Faeterna.Scripts.Menus.DeathScreen._continueButton, Faeterna.Scripts.Menus.DeathScreen._returnButton, Faeterna.Scripts.Menus.DeathScreen.OnContinuarPressed, Faeterna.Scripts.Menus.DeathScreen.OnReturnPressed.
void Faeterna.Scripts.Menus.DeathScreen.OnContinuarPressed()
Reanuda la partida desde el último guardado del slot activo.
Reproduce la animación del botón y luego cambia a la escena guardada.
References Faeterna.Scripts.Menus.DeathScreen._continueButton, Faeterna.Scripts.Menus.DeathScreen.ContinueFromLastSaveAsync, Faeterna.Scripts.Tools.ButtonTools.PlayPressAnimation.
Referenced by Faeterna.Scripts.Menus.DeathScreen._Ready.
void Faeterna.Scripts.Menus.DeathScreen.OnReturnPressed()
Devuelve al jugador al menú principal.
References Faeterna.Scripts.Menus.DeathScreen._returnButton, Faeterna.Scripts.Tools.ButtonTools.PlayPressAnimation.
Referenced by Faeterna.Scripts.Menus.DeathScreen._Ready.
void Faeterna.Scripts.Menus.DeathScreen.ChangeVisibility(bool visible)
Muestra la pantalla de muerte con un fade-in suave.
visible Indica si la pantalla debe mostrarse. Solo actúa cuando es true.
References Faeterna.Scripts.Menus.DeathScreen.FadeInDuration.
async Task Faeterna.Scripts.Menus.DeathScreen.ContinueFromLastSaveAsync()
Carga la partida guardada más reciente del slot activo y vuelve a la escena asociada.
Si no existe una escena guardada válida, usa la escena principal por defecto.
References Faeterna.Scripts.Menus.DeathScreen.DefaultGameScenePath, Faeterna.Scripts.Tools.GameSaveService.LoadActiveSlotAsync.
Referenced by Faeterna.Scripts.Menus.DeathScreen.OnContinuarPressed.