Faeterna::scripts::Personaje::TerrainParticles
RayCast2D Faeterna.scripts.Personaje.TerrainParticles._rayCast
RayCast2D que se usará para detectar el tile debajo del personaje y cambiar el atlas de partículas según la "RutaParticula" definida en el TileData.
Referenced by Faeterna.scripts.Personaje.TerrainParticles._Process.
AtlasTexture Faeterna.scripts.Personaje.TerrainParticles._atlasTextureId1
Atlas de partículas para la id 1 (por ejemplo: hierba).
Referenced by Faeterna.scripts.Personaje.TerrainParticles._Ready.
AtlasTexture Faeterna.scripts.Personaje.TerrainParticles._atlasTextureId2
Atlas de partículas para la id 2 (otra ruta/sprites distintos).
Referenced by Faeterna.scripts.Personaje.TerrainParticles._Ready.
Vector2I Faeterna.scripts.Personaje.TerrainParticles._frameSize
Tamaño en pixeles de cada frame del spritesheet.
Referenced by Faeterna.scripts.Personaje.TerrainParticles.ApplySpriteSheetLayout.
bool Faeterna.scripts.Personaje.TerrainParticles._freezeRandomFrameOnSpawn
Si es true, cada partícula se queda en el frame aleatorio con el que nace.
Referenced by Faeterna.scripts.Personaje.TerrainParticles.ConfigureProcessMaterialRandomFrame.
readonly Dictionary<int, AtlasTexture> Faeterna.scripts.Personaje.TerrainParticles._sourceAtlases
Mapa de RutaParticula -> atlas que se debe usar.
Referenced by Faeterna.scripts.Personaje.TerrainParticles._Ready.
readonly Dictionary<int, AtlasTexture> Faeterna.scripts.Personaje.TerrainParticles._runtimeAtlases
Copias en runtime para poder cambiar la región sin alterar el recurso compartido.
Referenced by Faeterna.scripts.Personaje.TerrainParticles._Process, Faeterna.scripts.Personaje.TerrainParticles._Ready.
int Faeterna.scripts.Personaje.TerrainParticles._currentTextureId
Id del atlas actualmente asignado a la propiedad Texture. Se usa para evitar reasignar el mismo atlas y resetear la animación de partículas innecesariamente.
Referenced by Faeterna.scripts.Personaje.TerrainParticles._Process, Faeterna.scripts.Personaje.TerrainParticles._Ready.
override void Faeterna.scripts.Personaje.TerrainParticles._Ready()
En _Ready se configuran los atlas de partículas a usar según lo asignado en el inspector y se hacen copias para modificar en runtime sin afectar los recursos originales.
También se configura el material de proceso para que cada partícula elija un frame aleatorio al nacer, y se asigna el atlas inicial (id 1) a la propiedad Texture.
References Faeterna.scripts.Personaje.TerrainParticles._atlasTextureId1, Faeterna.scripts.Personaje.TerrainParticles._atlasTextureId2, Faeterna.scripts.Personaje.TerrainParticles._currentTextureId, Faeterna.scripts.Personaje.TerrainParticles._runtimeAtlases, Faeterna.scripts.Personaje.TerrainParticles._sourceAtlases, Faeterna.scripts.Personaje.TerrainParticles.ApplySpriteSheetLayout, Faeterna.scripts.Personaje.TerrainParticles.ConfigureProcessMaterialRandomFrame.
override void Faeterna.scripts.Personaje.TerrainParticles._Process(double delta)
En cada frame, el método verifica si el RayCast2D está colisionando con un TileMapLayer.
Si es así, obtiene las coordenadas del tile debajo del personaje y revisa si tiene datos personalizados para "RutaParticula". Si encuentra una ruta válida, cambia el atlas de partículas a la correspondiente a esa ruta. Si la ruta no es válida o no hay colisión, mantiene el atlas actual. delta Tiempo en segundos desde el último frame. No se usa directamente en este método, pero es parte de la firma requerida por Godot para el método _Process.
References Faeterna.scripts.Personaje.TerrainParticles._currentTextureId, Faeterna.scripts.Personaje.TerrainParticles._rayCast, Faeterna.scripts.Personaje.TerrainParticles._runtimeAtlases, Faeterna.scripts.Personaje.TerrainParticles.ApplySpriteSheetLayout.
void Faeterna.scripts.Personaje.TerrainParticles.ApplySpriteSheetLayout(AtlasTexture atlasTexture)
Calcula y aplica el número de frames horizontales y verticales a usar en el shader de partículas según el tamaño del frame definido y el tamaño del atlas.
Si el atlas no es válido o el tamaño del frame no es positivo, se asigna 1 frame en ambas direcciones para evitar divisiones por cero o comportamientos inesperados. atlasTexture El AtlasTexture del cual se quiere calcular el layout de frames. Se espera que este atlas ya tenga asignada la región correcta si es que se usan regiones dentro de un atlas más grande.
References Faeterna.scripts.Personaje.TerrainParticles._frameSize.
Referenced by Faeterna.scripts.Personaje.TerrainParticles._Process, Faeterna.scripts.Personaje.TerrainParticles._Ready.
void Faeterna.scripts.Personaje.TerrainParticles.ConfigureProcessMaterialRandomFrame()
Configura el material de proceso para que cada partícula elija un frame aleatorio al nacer.
Esto se logra asignando un rango de offset de animación entre 0 y 1, lo que hace que el shader escoja un punto aleatorio en la animación para cada partícula. Si la opción _freezeRandomFrameOnSpawn está activada, también se establece la velocidad de animación a 0 para que las partículas no cambien de frame después de nacer.
References Faeterna.scripts.Personaje.TerrainParticles._freezeRandomFrameOnSpawn.
Referenced by Faeterna.scripts.Personaje.TerrainParticles._Ready.