Faeterna::Scripts::Personaje::Lira
const float Faeterna.Scripts.Personaje.Lira.Speed
Velocidad horizontal configurada del jugador (px/s).
Referenced by Faeterna.Scripts.Personaje.MaquinasDeEstados.Movimiento.States.StartPrayMovementState.Update.
const float Faeterna.Scripts.Personaje.Lira.JumpVelocity
Velocidad vertical aplicada al iniciar un salto (negativa = hacia arriba).
float Faeterna.Scripts.Personaje.Lira.Gravity
Gravedad usada en los estados aéreos. Se obtiene del ProjectSettings.
bool Faeterna.Scripts.Personaje.Lira._haveDobleJump
Flags de habilidades. Estas variables indican si el personaje ha adquirido ciertas habilidades (doble salto, dash) a lo largo del juego. Son usadas por la máquina de estados para determinar qué acciones están disponibles para el jugador en cada momento. Aunque podrían ser parte de un sistema de progresión más complejo, en este caso se manejan directamente en el personaje para simplificar su acceso desde los estados de movimiento.
Referenced by Faeterna.Scripts.Personaje.Lira.ApplySaveData, Faeterna.Scripts.Personaje.Lira.BuildSaveData.
bool Faeterna.Scripts.Personaje.Lira._haveDash
Flags de habilidades. Estas variables indican si el personaje ha adquirido ciertas habilidades (doble salto, dash) a lo largo del juego. Son usadas por la máquina de estados para determinar qué acciones están disponibles para el jugador en cada momento. Aunque podrían ser parte de un sistema de progresión más complejo, en este caso se manejan directamente en el personaje para simplificar su acceso desde los estados de movimiento.
Referenced by Faeterna.Scripts.Personaje.Lira.ApplySaveData, Faeterna.Scripts.Personaje.Lira.BuildSaveData.
const int Faeterna.Scripts.Personaje.Lira.Health
Puntos de vida máximos del personaje.
Referenced by Faeterna.Scripts.Personaje.Lira.ApplySaveData, Faeterna.Scripts.Personaje.Lira.BuildSaveData, Faeterna.Scripts.Personaje.Lira.Heal.
const int Faeterna.Scripts.Personaje.Lira.Mana
Maná máximo del personaje.
Referenced by Faeterna.Scripts.Personaje.Lira.ApplySaveData, Faeterna.Scripts.Personaje.Lira.BuildSaveData, Faeterna.Scripts.Personaje.Lira.RecoverMana, Faeterna.Scripts.Personaje.Lira.UpdateMana, Faeterna.Scripts.Personaje.Lira.UseMana.
const float Faeterna.Scripts.Personaje.Lira.KnockbackForceX
Fuerza horizontal del knockback al recibir daño.
Referenced by Faeterna.Scripts.Personaje.Lira.TakeDamage.
const float Faeterna.Scripts.Personaje.Lira.KnockbackForceY
Fuerza vertical del knockback al recibir daño (negativa = hacia arriba).
Referenced by Faeterna.Scripts.Personaje.Lira.TakeDamage.
int Faeterna.Scripts.Personaje.Lira._currentHealth
Puntos de vida actuales del personaje.
Referenced by Faeterna.Scripts.Personaje.Lira.ApplySaveData, Faeterna.Scripts.Personaje.Lira.BuildSaveData, Faeterna.Scripts.Personaje.Lira.Heal, Faeterna.Scripts.Personaje.Lira.TakeDamage, Faeterna.Scripts.Personaje.Lira.UpdateHearts.
float Faeterna.Scripts.Personaje.Lira._currentMana
Maná actual del personaje.
Referenced by Faeterna.Scripts.Personaje.Lira.ApplySaveData, Faeterna.Scripts.Personaje.Lira.BuildSaveData, Faeterna.Scripts.Personaje.Lira.RecoverMana, Faeterna.Scripts.Personaje.Lira.UpdateMana, Faeterna.Scripts.Personaje.Lira.UseMana.
Vector2 Faeterna.Scripts.Personaje.Lira.cameraInitPos
bool Faeterna.Scripts.Personaje.Lira.DoubleJumpAvailable
Indica si el doble salto está disponible.
Referenced by Faeterna.Scripts.Personaje.Lira.ApplySaveData, Faeterna.Scripts.Personaje.Lira.BuildSaveData.
bool Faeterna.Scripts.Personaje.Lira.DashAvailable
Indica si el dash está disponible.
Referenced by Faeterna.Scripts.Personaje.Lira.ApplySaveData, Faeterna.Scripts.Personaje.Lira.BuildSaveData.
bool Faeterna.Scripts.Personaje.Lira.CoyoteAvailable
Indica si el coyote time está disponible (permite saltar brevemente tras abandonar el suelo).
Referenced by Faeterna.Scripts.Personaje.Lira.ApplySaveData, Faeterna.Scripts.Personaje.Lira.BuildSaveData.
AnimatedSprite2D Faeterna.Scripts.Personaje.Lira.animatedSprite
Referencia al nodo AnimatedSprite2D hijo que muestra las animaciones del personaje.
Referenced by Faeterna.Scripts.Personaje.Lira._Ready, Faeterna.Scripts.Personaje.Lira.SetAnimation.
MovementStateMachine Faeterna.Scripts.Personaje.Lira.MovementStateMachine
Referencia a la máquina de estados de movimiento.
Referenced by Faeterna.Scripts.Personaje.Lira._Ready, Faeterna.Scripts.Personaje.Lira.TakeDamage, Faeterna.Scripts.Personaje.Lira.UpdateHearts.
LiraAnimationTree Faeterna.Scripts.Personaje.Lira.AnimTree
Controlador del AnimationTree — sincroniza animaciones con el estado de movimiento.
Referenced by Faeterna.Scripts.Personaje.Lira._Ready, Faeterna.Scripts.Personaje.Lira.UpdateHearts.
bool Faeterna.Scripts.Personaje.Lira.ItsFliped
bool Faeterna.Scripts.Personaje.Lira.IsInvulnerableByState
Array<TextureRect> Faeterna.Scripts.Personaje.Lira._hearts
Lista de TextureRect que representan los corazones de vida en la interfaz.
Referenced by Faeterna.Scripts.Personaje.Lira.UpdateHearts.
TextureRect Faeterna.Scripts.Personaje.Lira._manaBar
TextureRect que representa la barra de maná en la interfaz.
Referenced by Faeterna.Scripts.Personaje.Lira.UpdateMana.
TerrainParticles Faeterna.Scripts.Personaje.Lira.terrainParticles
Nodo que emite partículas al caminar sobre el terreno.
Se activa/desactiva desde los estados de movimiento para mejorar la inmersión visual.
CpuParticles2D Faeterna.Scripts.Personaje.Lira.saltoParticulas
CpuParticles2D Faeterna.Scripts.Personaje.Lira.dobleSaltoParticulas
DeathScreen Faeterna.Scripts.Personaje.Lira._deathScreen
Referencias a nodos de la interfaz y otros elementos relacionados con la salud, maná, muerte y descripción de objetos. Estos nodos se asignan desde el editor y se usan para actualizar visualmente la interfaz (corazones, barra de maná) y mostrar pantallas de muerte o descripciones de objetos cuando sea necesario. Aunque podrían estar gestionados por un sistema de UI separado, en este caso se incluyen directamente en el personaje para facilitar su acceso desde los estados de movimiento y otros métodos del personaje.
ObjetoDescription Faeterna.Scripts.Personaje.Lira._objectoDescription
Nodo que muestra la descripción de objetos al interactuar con ellos. Se asigna desde el editor y se usa para mostrar información relevante sobre objetos del juego (nombre, descripción, efectos) cuando el jugador interactúa con ellos. Aunque podría ser parte de un sistema de interacción más amplio, en este caso se incluye directamente en el personaje para facilitar su acceso desde los estados de movimiento y otros métodos relacionados con la interacción.
Referenced by Faeterna.scripts.Mapa.Objeto.Recoger.
AudioStreamPlayer2D Faeterna.Scripts.Personaje.Lira.audioPlayer
Referencias a nodos relacionados con el audio del personaje.
El AudioStreamPlayer2D se usa para reproducir sonidos asociados a las acciones del personaje (correr, saltar, atacar, recibir daño). Los AudioStream representan los diferentes clips de audio que se asignan desde el editor y se reproducen según la acción realizada. Aunque podrían estar gestionados por un sistema de audio separado, en este caso se incluyen directamente en el personaje para facilitar su acceso desde los estados de movimiento y otros métodos relacionados con las acciones del personaje.
Referenced by Faeterna.Scripts.Personaje.Lira.PlayAudio.
AudioStream Faeterna.Scripts.Personaje.Lira._hitAudio
AudioStream Faeterna.Scripts.Personaje.Lira._runAudio
AudioStream Faeterna.Scripts.Personaje.Lira._jumpAudio
AudioStream Faeterna.Scripts.Personaje.Lira._fallAudio
AudioStream Faeterna.Scripts.Personaje.Lira._attackAudio
AudioStream Faeterna.Scripts.Personaje.Lira._fireBallAudio
AudioStream Faeterna.Scripts.Personaje.Lira._dashAudio
Camera2D Faeterna.Scripts.Personaje.Lira._camera
Timer Faeterna.Scripts.Personaje.Lira._invencibilityTimer
Timer que controla la duración de la invencibilidad tras recibir daño.
Referenced by Faeterna.Scripts.Personaje.Lira.TakeDamage.
Area2D Faeterna.Scripts.Personaje.Lira._shotArea
Áreas usadas para detectar colisiones de ataques (disparo y patada).
Area2D Faeterna.Scripts.Personaje.Lira._kickArea
PackedScene Faeterna.Scripts.Personaje.Lira._bullet
Escena del proyectil disparado por el personaje. Se instancia al atacar y se le asignan propiedades como dirección y posición.
bool Faeterna.Scripts.Personaje.Lira._tutorial
Flags de tutorial. Estas variables se usan para controlar eventos específicos del tutorial, como la aparición de mensajes o la activación de mecánicas. No afectan directamente a la jugabilidad, pero permiten personalizar la experiencia durante el tutorial.
Referenced by Faeterna.Scripts.Personaje.Lira.ApplySaveData, Faeterna.Scripts.Personaje.Lira.BuildSaveData.
override async void Faeterna.Scripts.Personaje.Lira._Ready()
Inicialización del nodo.
Obtiene la referencia al AnimatedSprite2D hijo.
References Faeterna.Scripts.Personaje.Lira.animatedSprite, Faeterna.Scripts.Personaje.Lira.AnimTree, Faeterna.Scripts.Personaje.Lira.MovementStateMachine, Faeterna.Scripts.Personaje.Lira.TryLoadFromActiveSlotAsync, Faeterna.Scripts.Personaje.Lira.UpdateHearts, Faeterna.Scripts.Personaje.Lira.UpdateMana.
PlayerSaveData Faeterna.Scripts.Personaje.Lira.BuildSaveData(Vector2 position)
Construye un objeto PlayerSaveData con el estado actual del personaje, incluyendo posición, salud, maná, habilidades adquiridas y flags de movimiento.
Este método se usa para guardar el progreso del jugador en checkpoints o al salir del juego. Es importante destacar que las flags de movimiento (DoubleJumpAvailable, DashAvailable, CoyoteAvailable) se guardan como true por defecto, ya que son transitorias y se manejan exclusivamente por la máquina de estados. Sin embargo, las habilidades adquiridas (HasDoubleJump, HasDash) se guardan con su valor actual para persistir el progreso del jugador en la adquisición de habilidades. Guardar las flags de movimiento con su valor actual podría causar inconsistencias al cargar el juego, como permitir saltos infinitos o dashes múltiples si el jugador guardó mientras tenía estas habilidades disponibles. position Posición mundial del personaje que se guardará en el progreso. Esta posición se usa para colocar al personaje correctamente al cargar el juego desde un checkpoint o al restaurar el progreso. Es importante que esta posición sea precisa y corresponda a un punto válido en la escena para evitar problemas de colisiones o ubicaciones no deseadas al cargar el juego. Generalmente, esta posición se obtiene del nodo del personaje (GlobalPosition) al momento de guardar el progreso. Un objeto PlayerSaveData que contiene la información necesaria para restaurar el estado del personaje al cargar el juego. Este objeto incluye la posición, salud, maná, habilidades adquiridas y flags de movimiento (aunque estas últimas se guardan como true por defecto). El objeto resultante se serializa y se almacena en el sistema de guardado para su posterior recuperación. Al cargar el juego, se aplicará esta información al personaje para restaurar su estado de manera consistente con el momento en que se guardó.
References Faeterna.Scripts.Personaje.Lira._currentHealth, Faeterna.Scripts.Personaje.Lira._currentMana, Faeterna.Scripts.Personaje.Lira._haveDash, Faeterna.Scripts.Personaje.Lira._haveDobleJump, Faeterna.Scripts.Personaje.Lira._tutorial, Faeterna.Scripts.Personaje.Lira.CoyoteAvailable, Faeterna.Scripts.Personaje.Lira.DashAvailable, Faeterna.Scripts.Personaje.Lira.DoubleJumpAvailable, Faeterna.Scripts.Personaje.Lira.Health, Faeterna.Scripts.Personaje.Lira.Mana.
Referenced by Faeterna.Scripts.Tools.Saves.SaveCheckpointAsync.
void Faeterna.Scripts.Personaje.Lira.ApplySaveData(PlayerSaveData saveData)
Aplica los datos de guardado al personaje, restaurando su posición, salud, maná, habilidades adquiridas y reseteando las flags de movimiento a true.
Este método se usa al cargar el juego desde un checkpoint o al restaurar el progreso para colocar al personaje en el estado correcto. Es importante destacar que las flags de movimiento (DoubleJumpAvailable, DashAvailable, CoyoteAvailable) se resetean a true independientemente del valor guardado, ya que son transitorias y se manejan exclusivamente por la máquina de estados. Sin embargo, las habilidades adquiridas (HasDoubleJump, HasDash) se restauran con su valor guardado para persistir el progreso del jugador en la adquisición de habilidades. Guardar las flags de movimiento con su valor actual podría causar inconsistencias al cargar el juego, como permitir saltos infinitos o dashes múltiples si el jugador cargó mientras tenía estas habilidades disponibles. Al aplicar los datos de guardado, se garantiza un estado limpio y consistente para el personaje al cargar desde cualquier punto del juego. saveData Un objeto PlayerSaveData que contiene la información guardada del personaje, incluyendo posición, salud, maná, habilidades adquiridas y flags de movimiento. Este objeto se obtiene al cargar el juego desde un checkpoint o al restaurar el progreso. Al aplicar esta información al personaje, se restaurará su estado de manera consistente con el momento en que se guardó, asegurando que la posición, salud, maná y habilidades sean correctos. Es importante destacar que las flags de movimiento (DoubleJumpAvailable, DashAvailable, CoyoteAvailable) se resetean a true independientemente del valor guardado para evitar inconsistencias en la jugabilidad al cargar el juego.
References Faeterna.Scripts.Personaje.Lira._currentHealth, Faeterna.Scripts.Personaje.Lira._currentMana, Faeterna.Scripts.Personaje.Lira._haveDash, Faeterna.Scripts.Personaje.Lira._haveDobleJump, Faeterna.Scripts.Personaje.Lira._tutorial, Faeterna.Scripts.Personaje.Lira.CoyoteAvailable, Faeterna.Scripts.Personaje.Lira.DashAvailable, Faeterna.Scripts.Personaje.Lira.DoubleJumpAvailable, Faeterna.Scripts.Tools.PlayerSaveData.HasCompletedTutorial, Faeterna.Scripts.Tools.PlayerSaveData.HasDash, Faeterna.Scripts.Tools.PlayerSaveData.HasDoubleJump, Faeterna.Scripts.Personaje.Lira.Health, Faeterna.Scripts.Tools.PlayerSaveData.Health, Faeterna.Scripts.Personaje.Lira.Mana, Faeterna.Scripts.Tools.PlayerSaveData.Mana, Faeterna.Scripts.Tools.PlayerSaveData.Position, Faeterna.Scripts.Personaje.Lira.RemoveCollectedObjectsFromScene, Faeterna.Scripts.Personaje.Lira.UpdateHearts, Faeterna.Scripts.Personaje.Lira.UpdateMana.
Referenced by Faeterna.Scripts.Personaje.Lira.TryLoadFromActiveSlotAsync.
void Faeterna.Scripts.Personaje.Lira.SetAnimation(string animationName)
Reproduce una animación en el AnimatedSprite2D hijo.
Método auxiliar usado por los estados para cambiar la animación.
References Faeterna.Scripts.Personaje.Lira.animatedSprite.
void Faeterna.Scripts.Personaje.Lira.PlayAudio(string audioName)
Reproduce un sonido específico según el nombre proporcionado.
Este método se usa para reproducir los diferentes efectos de sonido asociados a las acciones del personaje (correr, saltar, atacar, recibir daño). El método asigna el clip de audio correspondiente al AudioStreamPlayer2D y lo reproduce. Si se proporciona un nombre de audio desconocido, se imprime un error en la consola. Es importante asegurarse de que el AudioStreamPlayer2D esté correctamente asignado en el editor para evitar errores al intentar reproducir sonidos. audioName Nombre del audio a reproducir. Este nombre se usa para identificar qué clip de audio asignar al AudioStreamPlayer2D antes de reproducirlo. Los nombres válidos son: "run", "jump", "fall", "attack", "fireball", "dash", "hit" e "idle". Cada nombre corresponde a un clip de audio específico que debe ser asignado en el editor. Si se proporciona un nombre que no coincide con ninguno de los casos definidos, se imprimirá un error indicando que el nombre de audio es desconocido.
References Faeterna.Scripts.Personaje.Lira.audioPlayer.
Referenced by Faeterna.Scripts.Personaje.Lira.TakeDamage.
async void Faeterna.Scripts.Personaje.Lira.TakeDamage(int amount, Vector2 attackerPosition)
Aplica daño al personaje, reduciendo su salud y reproduciendo un efecto de flash en los corazones de la interfaz.
amount Cantidad de puntos de vida a restar. attackerPosition Posición mundial del atacante, usada para calcular la dirección del knockback.
References Faeterna.Scripts.Personaje.Lira._currentHealth, Faeterna.Scripts.Personaje.Lira._invencibilityTimer, Faeterna.Scripts.Personaje.Lira.KnockbackForceX, Faeterna.Scripts.Personaje.Lira.KnockbackForceY, Faeterna.Scripts.Personaje.Lira.MovementStateMachine, Faeterna.Scripts.Personaje.Lira.PlayAudio, Faeterna.Scripts.Personaje.Lira.UpdateHearts.
void Faeterna.Scripts.Personaje.Lira.Heal(int amount)
Cura al personaje, aumentando su salud hasta el máximo permitido y actualizando la interfaz.
amount Cantidad de puntos de vida a restaurar.
References Faeterna.Scripts.Personaje.Lira._currentHealth, Faeterna.Scripts.Personaje.Lira.Health, Faeterna.Scripts.Personaje.Lira.UpdateHearts.
Referenced by Faeterna.Scripts.Tools.CheckPoint.ActionSaveProgress.
void Faeterna.Scripts.Personaje.Lira.UseMana(float amount)
Consume maná del personaje y actualiza la barra de la interfaz.
amount Cantidad de maná a gastar.
References Faeterna.Scripts.Personaje.Lira._currentMana, Faeterna.Scripts.Personaje.Lira.Mana, Faeterna.Scripts.Personaje.Lira.UpdateMana.
void Faeterna.Scripts.Personaje.Lira.RecoverMana(float amount)
Recupera maná del personaje hasta el máximo permitido y actualiza la barra de la interfaz.
amount Cantidad de maná a recuperar.
References Faeterna.Scripts.Personaje.Lira._currentMana, Faeterna.Scripts.Personaje.Lira.Mana, Faeterna.Scripts.Personaje.Lira.UpdateMana.
Referenced by Faeterna.Scripts.Tools.CheckPoint.ActionSaveProgress.
void Faeterna.Scripts.Personaje.Lira.FlipH(bool value)
void Faeterna.Scripts.Personaje.Lira.Shooting(double manaCost, double shotBallScale)
void Faeterna.Scripts.Personaje.Lira.OnKickHitboxAreaEntered(Area2D area)
void Faeterna.Scripts.Personaje.Lira.GiveDoubleJump()
void Faeterna.Scripts.Personaje.Lira.GiveDash()
bool Faeterna.Scripts.Personaje.Lira.HasDoubleJump()
bool Faeterna.Scripts.Personaje.Lira.HasDash()
async Task Faeterna.Scripts.Personaje.Lira.TryLoadFromActiveSlotAsync()
Intenta cargar el progreso guardado desde la ranura activa.
Si se encuentra un guardado válido, se aplica al personaje. Si el guardado corresponde a una escena diferente a la actual, no se carga para evitar inconsistencias.
References Faeterna.Scripts.Personaje.Lira.ApplySaveData, Faeterna.Scripts.Tools.GameSaveService.LoadActiveSlotAsync, Faeterna.Scripts.Tools.GameData.PlayerData, Faeterna.Scripts.Personaje.Lira.RemoveDefeatedBossesFromScene, Faeterna.Scripts.Tools.GameSaveService.RetrieveAndClearPending, Faeterna.Scripts.Tools.GameData.ScenePath, Faeterna.Scripts.Tools.GameSaveService.SetDefeatedBosses, Faeterna.Scripts.Tools.GameSaveService.SetPendingGameData.
Referenced by Faeterna.Scripts.Personaje.Lira._Ready.
void Faeterna.Scripts.Personaje.Lira.RemoveCollectedObjectsFromScene()
Elimina de la escena los objetos que ya han sido recogidos por el jugador para evitar que reaparezcan tras recargar la escena desde un guardado.
Referenced by Faeterna.Scripts.Personaje.Lira.ApplySaveData.
void Faeterna.Scripts.Personaje.Lira.RemoveCollectedObjectsRecursive(Node node)
void Faeterna.Scripts.Personaje.Lira.RemoveDefeatedBossesFromScene(System.Collections.Generic.List< string > defeatedTypes)
Elimina de la escena los bosses cuyos identificadores aparecen en la lista de derrotados del guardado (para que no reaparezcan tras recargar la escena si han sido vencidos).
defeatedTypes Lista de nombres de tipos/identificadores de bosses derrotados.
Referenced by Faeterna.Scripts.Personaje.Lira.TryLoadFromActiveSlotAsync.
void Faeterna.Scripts.Personaje.Lira.RemoveDefeatedBossesRecursive(Node node, System.Collections.Generic.List< string > defeatedTypes)
void Faeterna.Scripts.Personaje.Lira.UpdateHearts()
Actualiza visualmente los corazones de la interfaz según la salud actual.
References Faeterna.Scripts.Personaje.Lira._currentHealth, Faeterna.Scripts.Personaje.Lira._hearts, Faeterna.Scripts.Personaje.Lira.AnimTree, Faeterna.Scripts.Personaje.Lira.MovementStateMachine.
Referenced by Faeterna.Scripts.Personaje.Lira._Ready, Faeterna.Scripts.Personaje.Lira.ApplySaveData, Faeterna.Scripts.Personaje.Lira.Heal, Faeterna.Scripts.Personaje.Lira.TakeDamage.
void Faeterna.Scripts.Personaje.Lira.UpdateMana()
Actualiza visualmente la barra de maná de la interfaz según el maná actual.
References Faeterna.Scripts.Personaje.Lira._currentMana, Faeterna.Scripts.Personaje.Lira._manaBar, Faeterna.Scripts.Personaje.Lira.Mana.
Referenced by Faeterna.Scripts.Personaje.Lira._Ready, Faeterna.Scripts.Personaje.Lira.ApplySaveData, Faeterna.Scripts.Personaje.Lira.RecoverMana, Faeterna.Scripts.Personaje.Lira.UseMana.