Faeterna::Scripts::Menus::ObjetoDescription
const string Faeterna.Scripts.Menus.ObjetoDescription.ItemsCsvPath
Ruta al archivo CSV con los datos de los items.
Referenced by Faeterna.Scripts.Menus.ObjetoDescription.CargarItemsSiHaceFalta.
const string Faeterna.Scripts.Menus.ObjetoDescription.ImageNodePath
Ruta del nodo de la imagen del item dentro de la escena.
Referenced by Faeterna.Scripts.Menus.ObjetoDescription.EnlazarNodosSiHaceFalta.
const string Faeterna.Scripts.Menus.ObjetoDescription.NameNodePath
Ruta del nodo que muestra el nombre del item.
Referenced by Faeterna.Scripts.Menus.ObjetoDescription.EnlazarNodosSiHaceFalta.
const string Faeterna.Scripts.Menus.ObjetoDescription.DescriptionNodePath
Ruta del nodo que muestra la descripción del item.
Referenced by Faeterna.Scripts.Menus.ObjetoDescription.EnlazarNodosSiHaceFalta.
const string Faeterna.Scripts.Menus.ObjetoDescription.HistoryNodePath
Ruta del nodo que muestra la historia o lore del item.
Referenced by Faeterna.Scripts.Menus.ObjetoDescription.EnlazarNodosSiHaceFalta.
readonly Dictionary<int, ItemData> Faeterna.Scripts.Menus.ObjetoDescription.ItemsCache
Caché estática con los datos de items cargados desde el CSV.
Referenced by Faeterna.Scripts.Menus.ObjetoDescription.CargarDatosDelItem, Faeterna.Scripts.Menus.ObjetoDescription.CargarItemsSiHaceFalta.
bool Faeterna.Scripts.Menus.ObjetoDescription._itemsCargados
Indica si la caché ya fue cargada al menos una vez.
Referenced by Faeterna.Scripts.Menus.ObjetoDescription.CargarItemsSiHaceFalta.
int Faeterna.Scripts.Menus.ObjetoDescription._itemId
Identificador del item que se mostrará en el menú.
Referenced by Faeterna.Scripts.Menus.ObjetoDescription._Input, Faeterna.Scripts.Menus.ObjetoDescription.CargarDatosDelItem, Faeterna.Scripts.Menus.ObjetoDescription.ChangeVisibility.
TextureRect Faeterna.Scripts.Menus.ObjetoDescription._imageAbility
Imagen asociada al item seleccionado.
Referenced by Faeterna.Scripts.Menus.ObjetoDescription.CargarDatosDelItem, Faeterna.Scripts.Menus.ObjetoDescription.EnlazarNodosSiHaceFalta.
Label Faeterna.Scripts.Menus.ObjetoDescription._nameAbility
Label donde se muestra el nombre del item.
Referenced by Faeterna.Scripts.Menus.ObjetoDescription.CargarDatosDelItem, Faeterna.Scripts.Menus.ObjetoDescription.EnlazarNodosSiHaceFalta.
Label Faeterna.Scripts.Menus.ObjetoDescription._descriptionAbility
Label donde se muestra la descripción del item.
Referenced by Faeterna.Scripts.Menus.ObjetoDescription.CargarDatosDelItem, Faeterna.Scripts.Menus.ObjetoDescription.EnlazarNodosSiHaceFalta.
Label Faeterna.Scripts.Menus.ObjetoDescription._historyAbility
Label donde se muestra la historia del item.
Referenced by Faeterna.Scripts.Menus.ObjetoDescription.CargarDatosDelItem, Faeterna.Scripts.Menus.ObjetoDescription.EnlazarNodosSiHaceFalta.
delegate void Faeterna.Scripts.Menus.ObjetoDescription.MenuClosedEventHandler()
Señal emitida cuando el menú de descripción se cierra.
override void Faeterna.Scripts.Menus.ObjetoDescription._Ready()
Inicializa el nodo, enlaza referencias si faltan y carga el item correspondiente.
References Faeterna.Scripts.Menus.ObjetoDescription.CargarDatosDelItem, Faeterna.Scripts.Menus.ObjetoDescription.EnlazarNodosSiHaceFalta.
void Faeterna.Scripts.Menus.ObjetoDescription.ChangeVisibility(bool visible, int itemId)
Muestra u oculta la ventana de descripción y, si se abre, carga el item indicado.
visible Indica si la ventana debe mostrarse. itemId Identificador del item a visualizar.
References Faeterna.Scripts.Menus.ObjetoDescription._itemId, Faeterna.Scripts.Menus.ObjetoDescription.CargarDatosDelItem, Faeterna.Scripts.Menus.ObjetoDescription.EnlazarNodosSiHaceFalta.
Referenced by Faeterna.Scripts.Menus.ObjetoDescription._Input.
override void Faeterna.Scripts.Menus.ObjetoDescription._Input(InputEvent ev)
Cierra la ventana cuando el jugador pulsa una tecla mientras está visible.
ev Evento de entrada recibido por el nodo.
References Faeterna.Scripts.Menus.ObjetoDescription._itemId, Faeterna.Scripts.Menus.ObjetoDescription.ChangeVisibility.
void Faeterna.Scripts.Menus.ObjetoDescription.EnlazarNodosSiHaceFalta()
Intenta enlazar los nodos de interfaz si no están asignados desde el inspector.
References Faeterna.Scripts.Menus.ObjetoDescription._descriptionAbility, Faeterna.Scripts.Menus.ObjetoDescription._historyAbility, Faeterna.Scripts.Menus.ObjetoDescription._imageAbility, Faeterna.Scripts.Menus.ObjetoDescription._nameAbility, Faeterna.Scripts.Menus.ObjetoDescription.DescriptionNodePath, Faeterna.Scripts.Menus.ObjetoDescription.HistoryNodePath, Faeterna.Scripts.Menus.ObjetoDescription.ImageNodePath, Faeterna.Scripts.Menus.ObjetoDescription.NameNodePath.
Referenced by Faeterna.Scripts.Menus.ObjetoDescription._Ready, Faeterna.Scripts.Menus.ObjetoDescription.ChangeVisibility.
void Faeterna.Scripts.Menus.ObjetoDescription.CargarDatosDelItem()
Carga y muestra los datos del item actual.
References Faeterna.Scripts.Menus.ObjetoDescription._descriptionAbility, Faeterna.Scripts.Menus.ObjetoDescription._historyAbility, Faeterna.Scripts.Menus.ObjetoDescription._imageAbility, Faeterna.Scripts.Menus.ObjetoDescription._itemId, Faeterna.Scripts.Menus.ObjetoDescription._nameAbility, Faeterna.Scripts.Menus.ObjetoDescription._textSet, Faeterna.Scripts.Menus.ObjetoDescription.AplicarImagen, Faeterna.Scripts.Menus.ObjetoDescription.CargarItemsSiHaceFalta, Faeterna.Scripts.Menus.ObjetoDescription.ItemsCache.
Referenced by Faeterna.Scripts.Menus.ObjetoDescription._Ready, Faeterna.Scripts.Menus.ObjetoDescription.ChangeVisibility.
void Faeterna.Scripts.Menus.ObjetoDescription.AplicarImagen(string resourcePath)
Aplica al control de imagen el recurso indicado si es una textura válida.
resourcePath Ruta del recurso a cargar.
Referenced by Faeterna.Scripts.Menus.ObjetoDescription.CargarDatosDelItem.
static void Faeterna.Scripts.Menus.ObjetoDescription.CargarItemsSiHaceFalta()
Carga los items desde el CSV si todavía no están en memoria.
References Faeterna.Scripts.Menus.ObjetoDescription._itemsCargados, Faeterna.Scripts.Menus.ObjetoDescription.ItemsCache, Faeterna.Scripts.Menus.ObjetoDescription.ItemsCsvPath.
Referenced by Faeterna.Scripts.Menus.ObjetoDescription.CargarDatosDelItem.
static void Faeterna.Scripts.Menus.ObjetoDescription._textSet(Label label, string value)
Asigna el texto de un Label de forma centralizada.
label Label a modificar. value Texto que se quiere mostrar.
Referenced by Faeterna.Scripts.Menus.ObjetoDescription.CargarDatosDelItem.