Faeterna::Scripts::Menus::PlayMenu
const string Faeterna.Scripts.Menus.PlayMenu.DefaultGameScenePath
const string Faeterna.Scripts.Menus.PlayMenu.ContinueTexturePath
Array<TextureButton> Faeterna.Scripts.Menus.PlayMenu._saveButtons
Array de botones que representan los espacios de guardado disponibles (slots).
Se asignan desde el editor a través de export variable. Los botones permiten seleccionar un espacio específico para cargar o guardar una partida. Es importante que estas referencias estén correctamente asignadas para que el menú de selección de partidas funcione correctamente.
Referenced by Faeterna.Scripts.Menus.PlayMenu.CacheDefaultSlotTextures, Faeterna.Scripts.Menus.PlayMenu.OnDeletePressed, Faeterna.Scripts.Menus.PlayMenu.OnSavePressed, Faeterna.Scripts.Menus.PlayMenu.RefreshSlotVisuals.
TextureButton Faeterna.Scripts.Menus.PlayMenu._deleteButton
Botón para eliminar la partida guardada en el espacio seleccionado.
Al hacer clic, borra los datos guardados del slot actual. Se asigna desde el editor a través de export variable. Es importante que esta referencia esté correctamente asignada para que el botón de eliminar funcione correctamente en el menú de selección de partidas.
Referenced by Faeterna.Scripts.Menus.PlayMenu.OnDeletePressed.
TextureButton Faeterna.Scripts.Menus.PlayMenu._backButton
Botón para volver desde el menú de selección de partidas al menú principal.
Al hacer clic, oculta este menú y vuelve a mostrar el menú anterior. Se asigna desde el editor a través de export variable. Es importante que esta referencia esté correctamente asignada para que el botón de retroceso funcione correctamente en el menú de selección de partidas.
Referenced by Faeterna.Scripts.Menus.PlayMenu.OnBackPressed.
Texture2D Faeterna.Scripts.Menus.PlayMenu._continueTexture
Textura que se muestra en los botones de guardado cuando existe una partida guardada en ese espacio, indicando que se puede continuar desde esa partida.
Se asigna desde el editor a través de export variable. Si no está asignada, se carga desde la ruta predeterminada. Es importante que esta referencia esté correctamente asignada para que las visuales de partidas guardadas funcionen correctamente en el menú de selección.
Referenced by Faeterna.Scripts.Menus.PlayMenu._Ready, Faeterna.Scripts.Menus.PlayMenu.RefreshSlotVisuals.
int Faeterna.Scripts.Menus.PlayMenu._selectedSlot
Índice del espacio de guardado actualmente seleccionado el menú de selección de partidas.
Referenced by Faeterna.Scripts.Menus.PlayMenu._Ready, Faeterna.Scripts.Menus.PlayMenu.OnDeletePressed, Faeterna.Scripts.Menus.PlayMenu.OnSavePressed, Faeterna.Scripts.Menus.PlayMenu.RefreshSlotVisuals.
bool Faeterna.Scripts.Menus.PlayMenu._deleteMode
Indica si el menú está esperando confirmación para borrar una partida.
Referenced by Faeterna.Scripts.Menus.PlayMenu._Ready, Faeterna.Scripts.Menus.PlayMenu.OnDeletePressed, Faeterna.Scripts.Menus.PlayMenu.OnSavePressed, Faeterna.Scripts.Menus.PlayMenu.RefreshSlotVisuals.
readonly List<Texture2D> Faeterna.Scripts.Menus.PlayMenu._defaultSlotTextures
Lista que cache las texturas predeterminadas de cada botón de espacio de guardado, para poder restaurarlas cuando se elimina una partida guardada.
Referenced by Faeterna.Scripts.Menus.PlayMenu.CacheDefaultSlotTextures, Faeterna.Scripts.Menus.PlayMenu.RefreshSlotVisuals.
override void Faeterna.Scripts.Menus.PlayMenu._Ready()
Se llama cuando el nodo entra en la escena.
Carga la textura de "Continue" si no está asignada desde el editor, guarda las texturas predeterminadas de todos los botones de slots, actualiza las visuales de los espacios de guardado, y configura los eventos de visibilidad para refrescar las visuales cada vez que el menú se abre.
References Faeterna.Scripts.Menus.PlayMenu._continueTexture, Faeterna.Scripts.Menus.PlayMenu._deleteMode, Faeterna.Scripts.Menus.PlayMenu._selectedSlot, Faeterna.Scripts.Menus.PlayMenu.CacheDefaultSlotTextures, Faeterna.Scripts.Menus.PlayMenu.RefreshSlotVisuals.
void Faeterna.Scripts.Menus.PlayMenu.OnSavePressed(int id)
Se llama cuando se presiona un botón de espacio de guardado.
Si NO estamos en modo delete, carga la partida. Si estamos en modo delete, marca el slot con borde rojo para ser eliminado. id Índice del botón de slot que fue presionado.
References Faeterna.Scripts.Menus.PlayMenu._deleteMode, Faeterna.Scripts.Menus.PlayMenu._saveButtons, Faeterna.Scripts.Menus.PlayMenu._selectedSlot, Faeterna.Scripts.Tools.GameSaveService.DeleteSlot, Faeterna.Scripts.Tools.ButtonTools.PlayPressAnimation, Faeterna.Scripts.Menus.PlayMenu.RefreshSlotVisuals, Faeterna.Scripts.Tools.GameSaveService.SetActiveSlot, Faeterna.Scripts.Menus.PlayMenu.UpdateSlotBorder.
void Faeterna.Scripts.Menus.PlayMenu.OnDeletePressed()
Se llama cuando se presiona el botón de eliminar.
Primer clic activa el modo delete para que selecciones un slot. Segundo clic (después de seleccionar un slot) elimina la partida guardada.
References Faeterna.Scripts.Menus.PlayMenu._deleteButton, Faeterna.Scripts.Menus.PlayMenu._deleteMode, Faeterna.Scripts.Menus.PlayMenu._saveButtons, Faeterna.Scripts.Menus.PlayMenu._selectedSlot, Faeterna.Scripts.Tools.ButtonTools.PlayPressAnimation, Faeterna.Scripts.Menus.PlayMenu.UpdateSlotBorder.
void Faeterna.Scripts.Menus.PlayMenu.OnBackPressed()
Se llama cuando se presiona el botón de retroceso.
Reproduce la animación de presión y luego oculta este menú, volviendo al menú anterior (generalmente el menú principal).
References Faeterna.Scripts.Menus.PlayMenu._backButton, Faeterna.Scripts.Tools.ButtonTools.PlayPressAnimation.
void Faeterna.Scripts.Menus.PlayMenu.UpdateSlotBorder(TextureButton button, bool isSelected)
Actualiza el color del botón de slot para indicar si está seleccionado para eliminación.
Si está seleccionado, el borde se tintará de rojo; si no, es blanco (normal). button Botón de slot a actualizar. isSelected Si true, se tinta de rojo; si false, de blanco.
Referenced by Faeterna.Scripts.Menus.PlayMenu.OnDeletePressed, Faeterna.Scripts.Menus.PlayMenu.OnSavePressed.
void Faeterna.Scripts.Menus.PlayMenu.CacheDefaultSlotTextures()
Guarda las texturas predeterminadas de cada botón de espacio de guardado en una lista cache.
Estas texturas se restauran cuando se elimina una partida guardada para mostrar nuevamente el estado "vacío" del slot.
References Faeterna.Scripts.Menus.PlayMenu._defaultSlotTextures, Faeterna.Scripts.Menus.PlayMenu._saveButtons.
Referenced by Faeterna.Scripts.Menus.PlayMenu._Ready.
void Faeterna.Scripts.Menus.PlayMenu.RefreshSlotVisuals()
Actualiza las visuales de todos los espacios de guardado.
Si existe una partida guardada en un slot, muestra la textura de "Continue"; si no, muestra la textura predeterminada del slot. También actualiza el texto de etiqueta de cada botón para mostrar el número del slot y resetea los bordes a color normal.
References Faeterna.Scripts.Menus.PlayMenu._continueTexture, Faeterna.Scripts.Menus.PlayMenu._defaultSlotTextures, Faeterna.Scripts.Menus.PlayMenu._deleteMode, Faeterna.Scripts.Menus.PlayMenu._saveButtons, Faeterna.Scripts.Menus.PlayMenu._selectedSlot, Faeterna.Scripts.Tools.GameSaveService.HasSave.
Referenced by Faeterna.Scripts.Menus.PlayMenu._Ready, Faeterna.Scripts.Menus.PlayMenu.OnSavePressed.