Faeterna::Scripts::Menus::OptionsMenu
OptionButton Faeterna.Scripts.Menus.OptionsMenu._antialiasing
Control para seleccionar el tipo de antialiasing. Permite elegir entre diferentes métodos de suavizado de bordes para mejorar la calidad visual del juego. Se asigna desde el editor a través de export variable. Es importante que esta referencia esté correctamente asignada para que el control de antialiasing funcione correctamente en el menú de opciones.
Referenced by Faeterna.Scripts.Menus.OptionsMenu.OnSavePressed.
OptionButton Faeterna.Scripts.Menus.OptionsMenu._vsync
Control para activar o desactivar VSync.
Permite sincronizar la tasa de refresco del juego con la frecuencia de actualización del monitor para evitar el tearing. Se asigna desde el editor a través de export variable. Es importante que esta referencia esté correctamente asignada para que el control de VSync funcione correctamente en el menú de opciones.
Referenced by Faeterna.Scripts.Menus.OptionsMenu.OnSavePressed.
OptionButton Faeterna.Scripts.Menus.OptionsMenu._screen
Control para seleccionar el modo de pantalla.
Permite elegir entre modo ventana, pantalla completa o sin bordes. Se asigna desde el editor a través de export variable. Es importante que esta referencia esté correctamente asignada para que el control de modo de pantalla funcione correctamente en el menú de opciones.
Referenced by Faeterna.Scripts.Menus.OptionsMenu.OnSavePressed.
OptionButton Faeterna.Scripts.Menus.OptionsMenu._fpslock
Control para activar o desactivar el bloqueo de FPS. Permite limitar la tasa de cuadros por segundo del juego para mejorar el rendimiento o reducir el consumo de energía. Al activar el bloqueo de FPS, se habilitan controles adicionales para configurar el valor del límite de FPS. Se asigna desde el editor a través de export variable. Es importante que esta referencia esté correctamente asignada para que el control de bloqueo de FPS funcione correctamente en el menú de opciones.
Referenced by Faeterna.Scripts.Menus.OptionsMenu.OnSavePressed.
HSlider Faeterna.Scripts.Menus.OptionsMenu._fpsslider
Controles para configurar el valor del límite de FPS cuando el bloqueo de FPS está activado. Permiten ajustar el límite de cuadros por segundo para equilibrar el rendimiento y la calidad visual según las preferencias del jugador. Estos controles solo están activos cuando el bloqueo de FPS está habilitado. Se asignan desde el editor a través de export variables. Es importante que estas referencias estén correctamente asignadas para que los controles de configuración de FPS funcionen correctamente en el menú de opciones.
SpinBox Faeterna.Scripts.Menus.OptionsMenu._fpsspinbox
Control para configurar el valor del límite de FPS cuando el bloqueo de FPS está activado. Permite ajustar el límite de cuadros por segundo para equilibrar el rendimiento y la calidad visual según las preferencias del jugador. Este control solo está activo cuando el bloqueo de FPS está habilitado. Se asigna desde el editor a través de export variable. Es importante que esta referencia esté correctamente asignada para que el control de configuración de FPS funcione correctamente en el menú de opciones.
OptionButton Faeterna.Scripts.Menus.OptionsMenu._shadows
Control para seleccionar la calidad de las sombras. Permite elegir entre diferentes niveles de calidad de sombras para mejorar la apariencia visual del juego. Se asigna desde el editor a través de export variable. Es importante que esta referencia esté correctamente asignada para que el control de calidad de sombras funcione correctamente en el menú de opciones.
Referenced by Faeterna.Scripts.Menus.OptionsMenu.OnSavePressed.
HSlider Faeterna.Scripts.Menus.OptionsMenu._master
Control para ajustar el volumen maestro del juego. Permite configurar el nivel general de volumen que afecta a todos los sonidos del juego. Se asigna desde el editor a través de export variable. Es importante que esta referencia esté correctamente asignada para que el control de volumen maestro funcione correctamente en el menú de opciones.
Referenced by Faeterna.Scripts.Menus.OptionsMenu.OnSavePressed.
SpinBox Faeterna.Scripts.Menus.OptionsMenu._masterSpinBox
Control para ajustar el volumen maestro del juego. Permite configurar el nivel general de volumen que afecta a todos los sonidos del juego. Se asigna desde el editor a través de export variable. Es importante que esta referencia esté correctamente asignada para que el control de volumen maestro funcione correctamente en el menú de opciones.
HSlider Faeterna.Scripts.Menus.OptionsMenu._music
Control para ajustar el volumen de la música del juego. Permite configurar el nivel de volumen específico para la música, lo que afecta a las pistas musicales del juego. Se asigna desde el editor a través de export variable. Es importante que esta referencia esté correctamente asignada para que el control de volumen de música funcione correctamente en el menú de opciones.
Referenced by Faeterna.Scripts.Menus.OptionsMenu.OnSavePressed.
SpinBox Faeterna.Scripts.Menus.OptionsMenu._musicSpinBox
Control para ajustar el volumen de la música del juego. Permite configurar el nivel de volumen específico para la música, lo que afecta a las pistas musicales del juego. Se asigna desde el editor a través de export variable. Es importante que esta referencia esté correctamente asignada para que el control de volumen de música funcione correctamente en el menú de opciones.
HSlider Faeterna.Scripts.Menus.OptionsMenu._soundfx
Control para ajustar el volumen de los efectos de sonido del juego. Permite configurar el nivel de volumen específico para los efectos de sonido, lo que afecta a los sonidos relacionados con acciones, interacciones y eventos en el juego. Se asigna desde el editor a través de export variable. Es importante que esta referencia esté correctamente asignada para que el control de volumen de efectos de sonido funcione correctamente en el menú de opciones.
Referenced by Faeterna.Scripts.Menus.OptionsMenu.OnSavePressed.
SpinBox Faeterna.Scripts.Menus.OptionsMenu._soundfxSpinBox
Control para ajustar el volumen de los efectos de sonido del juego. Permite configurar el nivel de volumen específico para los efectos de sonido, lo que afecta a los sonidos relacionados con acciones, interacciones y eventos en el juego. Se asigna desde el editor a través de export variable. Es importante que esta referencia esté correctamente asignada para que el control de volumen de efectos de sonido funcione correctamente en el menú de opciones.
HSlider Faeterna.Scripts.Menus.OptionsMenu._enviroment
Control para ajustar el volumen de los sonidos ambientales del juego. Permite configurar el nivel de volumen específico para los sonidos relacionados con el ambiente, como el viento, la lluvia, los animales, etc. Se asigna desde el editor a través de export variable. Es importante que esta referencia esté correctamente asignada para que el control de volumen de sonidos ambientales funcione correctamente en el menú de opciones.
Referenced by Faeterna.Scripts.Menus.OptionsMenu.OnSavePressed.
SpinBox Faeterna.Scripts.Menus.OptionsMenu._enviromentSpinBox
Control para ajustar el volumen de los sonidos ambientales del juego. Permite configurar el nivel de volumen específico para los sonidos relacionados con el ambiente, como el viento, la lluvia, los animales, etc. Se asigna desde el editor a través de export variable. Es importante que esta referencia esté correctamente asignada para que el control de volumen de sonidos ambientales funcione correctamente en el menú de opciones.
HSlider Faeterna.Scripts.Menus.OptionsMenu._uisound
Control para ajustar el volumen de los sonidos de la interfaz de usuario (UI) del juego. Permite configurar el nivel de volumen específico para los sonidos relacionados con la interfaz, como clics, notificaciones, etc. Se asigna desde el editor a través de export variable. Es importante que esta referencia esté correctamente asignada para que el control de volumen de sonidos UI funcione correctamente en el menú de opciones.
Referenced by Faeterna.Scripts.Menus.OptionsMenu.OnSavePressed.
SpinBox Faeterna.Scripts.Menus.OptionsMenu._uisoundSpinBox
Control para ajustar el volumen de los sonidos de la interfaz de usuario (UI) del juego. Permite configurar el nivel de volumen específico para los sonidos relacionados con la interfaz, como clics, notificaciones, etc. Se asigna desde el editor a través de export variable. Es importante que esta referencia esté correctamente asignada para que el control de volumen de sonidos UI funcione correctamente en el menú de opciones.
TextureButton Faeterna.Scripts.Menus.OptionsMenu._saveButton
Botón para guardar los cambios realizados en las opciones. Al hacer clic, guarda la configuración actual en el sistema de guardado para que se mantenga en futuras sesiones. Se asigna desde el editor a través de export variable. Es importante que esta referencia esté correctamente asignada para que el botón de guardar funcione correctamente en el menú de opciones.
Referenced by Faeterna.Scripts.Menus.OptionsMenu.OnSavePressed.
TextureButton Faeterna.Scripts.Menus.OptionsMenu._exitButton
Botón para salir del menú de opciones. Al hacer clic, cierra el menú de opciones y vuelve al menú principal o a la escena anterior. Se asigna desde el editor a través de export variable. Es importante que esta referencia esté correctamente asignada para que el botón de salir funcione correctamente en el menú de opciones.
Referenced by Faeterna.Scripts.Menus.OptionsMenu.OnExitPressed.
Saves Faeterna.Scripts.Menus.OptionsMenu._saveSettings
Instancia de la clase de guardado para cargar y guardar las opciones del juego. Permite persistir la configuración seleccionada por el jugador entre sesiones. Se utiliza para cargar las opciones al iniciar el menú y para guardar las opciones cuando se presiona el botón de guardar. Es importante que esta instancia esté correctamente inicializada para que el sistema de guardado funcione correctamente en el menú de opciones.
Referenced by Faeterna.Scripts.Menus.OptionsMenu._Ready, Faeterna.Scripts.Menus.OptionsMenu.OnSavePressed.
bool Faeterna.Scripts.Menus.OptionsMenu._isFpslock
Variable para rastrear si el bloqueo de FPS está activado. Se utiliza para habilitar o deshabilitar los controles de configuración de FPS y para aplicar el límite de FPS en tiempo real. Cuando el bloqueo de FPS está activado, se permite configurar el valor del límite de FPS; cuando está desactivado, se deshabilitan esos controles y se elimina cualquier límite de FPS aplicado. Es importante que esta variable esté correctamente gestionada para que la funcionalidad de bloqueo de FPS funcione correctamente en el menú de opciones.
Referenced by Faeterna.Scripts.Menus.OptionsMenu.OnHSliderFPSValueChanged, Faeterna.Scripts.Menus.OptionsMenu.OnOptionFPSButtonItemSelected, Faeterna.Scripts.Menus.OptionsMenu.OnSpinFPSBoxValueChanged.
int Faeterna.Scripts.Menus.OptionsMenu._fpsValue
Variable para almacenar el valor actual del límite de FPS cuando el bloqueo de FPS está activado. Se utiliza para aplicar el límite de FPS en tiempo real y para mostrar el valor actual en los controles de configuración de FPS. Este valor se actualiza cuando el jugador ajusta el límite de FPS a través de los controles del menú, y se aplica al motor para limitar la tasa de cuadros por segundo del juego. Es importante que esta variable esté correctamente gestionada para que la funcionalidad de bloqueo de FPS funcione correctamente en el menú de opciones. El valor predeterminado se establece en 60 FPS, pero puede ser ajustado por el jugador según sus preferencias.
Referenced by Faeterna.Scripts.Menus.OptionsMenu._Ready, Faeterna.Scripts.Menus.OptionsMenu.OnHSliderFPSValueChanged, Faeterna.Scripts.Menus.OptionsMenu.OnOptionFPSButtonItemSelected, Faeterna.Scripts.Menus.OptionsMenu.OnSavePressed, Faeterna.Scripts.Menus.OptionsMenu.OnSpinFPSBoxValueChanged.
override void Faeterna.Scripts.Menus.OptionsMenu._Ready()
Se llama cuando el nodo entra en la escena.
Carga las opciones guardadas previamente utilizando la clase de guardado y aplica cada configuración a los controles correspondientes del menú. Esto asegura que el menú de opciones refleje la configuración actual del juego al abrirlo, permitiendo al jugador ver y ajustar sus preferencias de video y audio según lo que se haya guardado en sesiones anteriores. Es importante que esta función esté correctamente implementada para que el menú de opciones funcione correctamente en términos de carga y aplicación de configuraciones guardadas.
References Faeterna.Scripts.Menus.OptionsMenu._fpsValue, Faeterna.Scripts.Menus.OptionsMenu._saveSettings, Faeterna.Scripts.Menus.OptionsMenu.OnHEnviromentSliderValueChanged, Faeterna.Scripts.Menus.OptionsMenu.OnHMasterSliderValueChanged, Faeterna.Scripts.Menus.OptionsMenu.OnHMusicSliderValueChanged, Faeterna.Scripts.Menus.OptionsMenu.OnHSoundFXSliderValueChanged, Faeterna.Scripts.Menus.OptionsMenu.OnHUISoundSliderValueChanged, Faeterna.Scripts.Menus.OptionsMenu.OnOptionButtonItemSelected, Faeterna.Scripts.Menus.OptionsMenu.OnOptionFPSButtonItemSelected, Faeterna.Scripts.Menus.OptionsMenu.OnOptionShadowButtonItemSelected, Faeterna.Scripts.Menus.OptionsMenu.OnVSyncButtonItemSelected, Faeterna.Scripts.Menus.OptionsMenu.OnWindowButtonItemSelected.
void Faeterna.Scripts.Menus.OptionsMenu.OnOptionButtonItemSelected(int index)
Se llama cuando se selecciona una opción en el control de antialiasing.
Aplica la configuración de antialiasing seleccionada al viewport del juego en tiempo real. Permite al jugador elegir entre diferentes métodos de suavizado de bordes para mejorar la calidad visual del juego según sus preferencias. Cada opción corresponde a un método específico de antialiasing, y al seleccionar una opción, se actualizan las configuraciones del viewport para reflejar esa elección. Es importante que esta función esté correctamente implementada para que el control de antialiasing funcione correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. index Índice de la opción seleccionada en el control de antialiasing. Cada índice corresponde a un método específico de antialiasing (por ejemplo, 0 para desactivado, 1 para FXAA, 2 para TAA, etc.). Este índice se utiliza para determinar qué configuración de antialiasing aplicar al viewport del juego. Es importante que los índices estén correctamente asignados en el control de antialiasing para que esta función funcione correctamente y aplique la configuración deseada según la selección del jugador.
Referenced by Faeterna.Scripts.Menus.OptionsMenu._Ready.
void Faeterna.Scripts.Menus.OptionsMenu.OnVSyncButtonItemSelected(int index)
Se llama cuando se selecciona una opción en el control de VSync.
Aplica la configuración de VSync seleccionada al juego en tiempo real. Permite al jugador activar o desactivar la sincronización vertical para evitar el tearing y mejorar la calidad visual del juego según sus preferencias. Al seleccionar una opción, se actualiza la configuración de VSync del juego para reflejar esa elección. Es importante que esta función esté correctamente implementada para que el control de VSync funcione correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. index Índice de la opción seleccionada en el control de VSync. Por ejemplo, 0 para desactivado y 1 para activado. Este índice se utiliza para determinar si se debe habilitar o deshabilitar la sincronización vertical en el juego. Es importante que los índices estén correctamente asignados en el control de VSync para que esta función funcione correctamente y aplique la configuración deseada según la selección del jugador.
Referenced by Faeterna.Scripts.Menus.OptionsMenu._Ready.
void Faeterna.Scripts.Menus.OptionsMenu.OnWindowButtonItemSelected(int index)
Se llama cuando se selecciona una opción en el control de modo de pantalla.
Aplica la configuración de modo de pantalla seleccionada al juego en tiempo real. Permite al jugador elegir entre diferentes modos de pantalla (ventana, pantalla completa, sin bordes) para adaptar la experiencia de juego a sus preferencias y necesidades. Al seleccionar una opción, se actualiza la configuración del modo de pantalla del juego para reflejar esa elección. Es importante que esta función esté correctamente implementada para que el control de modo de pantalla funcione correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. index Índice de la opción seleccionada en el control de modo de pantalla. Por ejemplo, 0 para modo ventana, 1 para pantalla completa y 2 para sin bordes. Este índice se utiliza para determinar qué modo de pantalla aplicar al juego. Es importante que los índices estén correctamente asignados en el control de modo de pantalla para que esta función funcione correctamente y aplique la configuración deseada según la selección del jugador.
Referenced by Faeterna.Scripts.Menus.OptionsMenu._Ready.
void Faeterna.Scripts.Menus.OptionsMenu.OnOptionFPSButtonItemSelected(int index)
Se llama cuando se selecciona una opción en el control de bloqueo de FPS.
Aplica la configuración de bloqueo de FPS seleccionada al juego en tiempo real. Permite al jugador activar o desactivar el bloqueo de FPS para limitar la tasa de cuadros por segundo del juego según sus preferencias. Al activar el bloqueo de FPS, se habilitan controles adicionales para configurar el valor del límite de FPS; al desactivarlo, se deshabilitan esos controles y se elimina cualquier límite de FPS aplicado. Es importante que esta función esté correctamente implementada para que el control de bloqueo de FPS funcione correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. index Índice de la opción seleccionada en el control de bloqueo de FPS. Por ejemplo, 0 para desactivado y 1 para activado. Este índice se utiliza para determinar si se debe habilitar o deshabilitar el bloqueo de FPS en el juego. Es importante que los índices estén correctamente asignados en el control de bloqueo de FPS para que esta función funcione correctamente y aplique la configuración deseada según la selección del jugador. Además, al activar el bloqueo de FPS, se deben habilitar los controles para configurar el valor del límite de FPS, y al desactivarlo, se deben deshabilitar esos controles y eliminar cualquier límite de FPS aplicado.
References Faeterna.Scripts.Menus.OptionsMenu._fpsValue, Faeterna.Scripts.Menus.OptionsMenu._isFpslock.
Referenced by Faeterna.Scripts.Menus.OptionsMenu._Ready.
void Faeterna.Scripts.Menus.OptionsMenu.OnHSliderFPSValueChanged(float value)
Se llama cuando se cambia el valor del control de configuración de FPS (slider o spinbox).
Aplica el nuevo valor del límite de FPS al juego en tiempo real. Permite al jugador ajustar el límite de cuadros por segundo para equilibrar el rendimiento y la calidad visual según sus preferencias. Este método se llama tanto desde el slider como desde el spinbox para asegurarse de que ambos controles estén sincronizados y reflejen el mismo valor. Es importante que esta función esté correctamente implementada para que los controles de configuración de FPS funcionen correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego cuando el bloqueo de FPS está activado. value Nuevo valor del límite de FPS seleccionado por el jugador a través del slider o spinbox. Este valor se utiliza para actualizar la configuración de FPS del juego en tiempo real, permitiendo al jugador ajustar la tasa de cuadros por segundo según sus preferencias. Es importante que este valor se gestione correctamente para que los controles de configuración de FPS funcionen correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego cuando el bloqueo de FPS está activado. Además, este valor debe mantenerse sincronizado entre el slider y el spinbox para reflejar la misma configuración de FPS en ambos controles.
References Faeterna.Scripts.Menus.OptionsMenu._fpsValue, Faeterna.Scripts.Menus.OptionsMenu._isFpslock.
void Faeterna.Scripts.Menus.OptionsMenu.OnSpinFPSBoxValueChanged(float value)
Se llama cuando se cambia el valor del control de configuración de FPS (slider o spinbox).
Aplica el nuevo valor del límite de FPS al juego en tiempo real. Permite al jugador ajustar el límite de cuadros por segundo para equilibrar el rendimiento y la calidad visual según sus preferencias. Este método se llama tanto desde el slider como desde el spinbox para asegurarse de que ambos controles estén sincronizados y reflejen el mismo valor. Es importante que esta función esté correctamente implementada para que los controles de configuración de FPS funcionen correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego cuando el bloqueo de FPS está activado. value Nuevo valor del límite de FPS seleccionado por el jugador a través del slider o spinbox. Este valor se utiliza para actualizar la configuración de FPS del juego en tiempo real, permitiendo al jugador ajustar la tasa de cuadros por segundo según sus preferencias. Es importante que este valor se gestione correctamente para que los controles de configuración de FPS funcionen correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego cuando el bloqueo de FPS está activado. Además, este valor debe mantenerse sincronizado entre el slider y el spinbox para reflejar la misma configuración de FPS en ambos controles.
References Faeterna.Scripts.Menus.OptionsMenu._fpsValue, Faeterna.Scripts.Menus.OptionsMenu._isFpslock.
void Faeterna.Scripts.Menus.OptionsMenu.OnOptionShadowButtonItemSelected(int index)
Se llama cuando se selecciona una opción en el control de calidad de sombras.
Aplica la configuración de calidad de sombras seleccionada al juego en tiempo real. Permite al jugador elegir entre diferentes niveles de calidad de sombras para mejorar la apariencia visual del juego según sus preferencias. Al seleccionar una opción, se actualiza la configuración de calidad de sombras del juego para reflejar esa elección. Es importante que esta función esté correctamente implementada para que el control de calidad de sombras funcione correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. Además, esta función maneja posibles excepciones al aplicar la configuración de sombras, especialmente en entornos sin backend gráfico, para garantizar que el juego no se bloquee y que se informe adecuadamente al jugador si no se pueden aplicar las configuraciones seleccionadas. index Índice de la opción seleccionada en el control de calidad de sombras. Cada índice corresponde a un nivel específico de calidad de sombras (por ejemplo, 0 para Hard, 1 para Soft Very Low, 2 para Soft Low, etc.). Este índice se utiliza para determinar qué configuración de calidad de sombras aplicar al juego. Es importante que los índices estén correctamente asignados en el control de calidad de sombras para que esta función funcione correctamente y aplique la configuración deseada según la selección del jugador. Además, esta función debe manejar posibles excepciones al aplicar la configuración de sombras, especialmente en entornos sin backend gráfico, para garantizar que el juego no se bloquee y que se informe adecuadamente al jugador si no se pueden aplicar las configuraciones seleccionadas.
References Faeterna.Scripts.Menus.OptionsMenu.ApplyShadowQuality.
Referenced by Faeterna.Scripts.Menus.OptionsMenu._Ready.
void Faeterna.Scripts.Menus.OptionsMenu.OnHMasterSliderValueChanged(float value)
Se llama cuando se cambia el valor del control de volumen maestro (slider o spinbox).
Aplica el nuevo valor de volumen maestro al sistema de audio del juego en tiempo real. Permite al jugador ajustar el nivel general de volumen que afecta a todos los sonidos del juego. Este método se llama tanto desde el slider como desde el spinbox para asegurarse de que ambos controles estén sincronizados y reflejen el mismo valor. Es importante que esta función esté correctamente implementada para que los controles de volumen maestro funcionen correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. Además, esta función utiliza la función NormalizeVolumeToDb para convertir el valor de porcentaje a decibelios antes de aplicarlo al sistema de audio. value Nuevo valor de volumen maestro en porcentaje (0-100) seleccionado por el jugador a través del slider o spinbox. Este valor se utiliza para actualizar el nivel de volumen maestro en el sistema de audio del juego en tiempo real, permitiendo al jugador ajustar el volumen general del juego según sus preferencias. Es importante que este valor se gestione correctamente para que los controles de volumen maestro funcionen correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. Además, esta función utiliza la función NormalizeVolumeToDb para convertir el valor de porcentaje a decibelios antes de aplicarlo al sistema de audio.
References Faeterna.Scripts.Menus.OptionsMenu.NormalizeVolumeToDb.
Referenced by Faeterna.Scripts.Menus.OptionsMenu._Ready.
void Faeterna.Scripts.Menus.OptionsMenu.OnHMusicSliderValueChanged(float value)
Se llama cuando se cambia el valor del control de volumen de música (slider o spinbox).
Aplica el nuevo valor de volumen de música al sistema de audio del juego en tiempo real. Permite al jugador ajustar el nivel de volumen específico para la música, lo que afecta a las pistas musicales del juego. Este método se llama tanto desde el slider como desde el spinbox para asegurarse de que ambos controles estén sincronizados y reflejen el mismo valor. Es importante que esta función esté correctamente implementada para que los controles de volumen de música funcionen correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. Además, esta función utiliza la función NormalizeVolumeToDb para convertir el valor de porcentaje a decibelios antes de aplicarlo al sistema de audio. value Nuevo valor de volumen de música en porcentaje (0-100) seleccionado por el jugador a través del slider o spinbox. Este valor se utiliza para actualizar el nivel de volumen de la música en el sistema de audio del juego en tiempo real, permitiendo al jugador ajustar el volumen específico para las pistas musicales del juego según sus preferencias. Es importante que este valor se gestione correctamente para que los controles de volumen de música funcionen correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. Además, esta función utiliza la función NormalizeVolumeToDb para convertir el valor de porcentaje a decibelios antes de aplicarlo al sistema de audio.
References Faeterna.Scripts.Menus.OptionsMenu.NormalizeVolumeToDb.
Referenced by Faeterna.Scripts.Menus.OptionsMenu._Ready.
void Faeterna.Scripts.Menus.OptionsMenu.OnHSoundFXSliderValueChanged(float value)
Se llama cuando se cambia el valor del control de volumen de efectos de sonido (slider o spinbox).
Aplica el nuevo valor de volumen de efectos de sonido al sistema de audio del juego en tiempo real. Permite al jugador ajustar el nivel de volumen específico para los efectos de sonido, lo que afecta a los sonidos relacionados con acciones, interacciones y eventos en el juego. Este método se llama tanto desde el slider como desde el spinbox para asegurarse de que ambos controles estén sincronizados y reflejen el mismo valor. Es importante que esta función esté correctamente implementada para que los controles de volumen de efectos de sonido funcionen correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. Además, esta función utiliza la función NormalizeVolumeToDb para convertir el valor de porcentaje a decibelios antes de aplicarlo al sistema de audio. value Nuevo valor de volumen de efectos de sonido en porcentaje (0-100) seleccionado por el jugador a través del slider o spinbox. Este valor se utiliza para actualizar el nivel de volumen de los efectos de sonido en el sistema de audio del juego en tiempo real, permitiendo al jugador ajustar el volumen específico para los sonidos relacionados con acciones, interacciones y eventos en el juego según sus preferencias. Es importante que este valor se gestione correctamente para que los controles de volumen de efectos de sonido funcionen correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. Además, esta función utiliza la función NormalizeVolumeToDb para convertir el valor de porcentaje a decibelios antes de aplicarlo al sistema de audio.
References Faeterna.Scripts.Menus.OptionsMenu.NormalizeVolumeToDb.
Referenced by Faeterna.Scripts.Menus.OptionsMenu._Ready.
void Faeterna.Scripts.Menus.OptionsMenu.OnHEnviromentSliderValueChanged(float value)
Se llama cuando se cambia el valor del control de volumen de ambiente (slider o spinbox).
Aplica el nuevo valor de volumen de ambiente al sistema de audio del juego en tiempo real. Permite al jugador ajustar el nivel de volumen específico para los sonidos ambientales, lo que afecta a los sonidos relacionados con el entorno del juego, como el viento, la lluvia, los animales, etc. Este método se llama tanto desde el slider como desde el spinbox para asegurarse de que ambos controles estén sincronizados y reflejen el mismo valor. Es importante que esta función esté correctamente implementada para que los controles de volumen de ambiente value Nuevo valor de volumen de ambiente en porcentaje (0-100) seleccionado por el jugador a través del slider o spinbox. Este valor se utiliza para actualizar el nivel de volumen de los sonidos ambientales en el sistema de audio del juego en tiempo real, permitiendo al jugador ajustar el volumen específico para los sonidos relacionados con el entorno del juego según sus preferencias. Es importante que este valor se gestione correctamente para que los controles de volumen de ambiente funcionen correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. Además, esta función utiliza la función NormalizeVolumeToDb para convertir el valor de porcentaje a decibelios antes de aplicarlo al sistema de audio.
References Faeterna.Scripts.Menus.OptionsMenu.NormalizeVolumeToDb.
Referenced by Faeterna.Scripts.Menus.OptionsMenu._Ready.
void Faeterna.Scripts.Menus.OptionsMenu.OnHUISoundSliderValueChanged(float value)
Se llama cuando se cambia el valor del control de volumen de sonido de interfaz (slider o spinbox).
Aplica el nuevo valor de volumen de sonido de interfaz al sistema de audio del juego en tiempo real. Permite al jugador ajustar el nivel de volumen específico para los sonidos relacionados con la interfaz del juego, como los clics, las notificaciones, los menús, etc. Este método se llama tanto desde el slider como desde el spinbox para asegurarse de que ambos controles estén sincronizados y reflejen el mismo valor. Es importante que esta función esté correctamente implementada para que los controles de volumen de sonido de interfaz funcionen correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. Además, esta función utiliza la función NormalizeVolumeToDb para convertir el valor de porcentaje a decibelios antes de aplicarlo al sistema de audio. value Nuevo valor de volumen de sonido de interfaz en porcentaje (0-100) seleccionado por el jugador a través del slider o spinbox. Este valor se utiliza para actualizar el nivel de volumen de los sonidos relacionados con la interfaz del juego en el sistema de audio del juego en tiempo real, permitiendo al jugador ajustar el volumen específico para los sonidos de la interfaz según sus preferencias. Es importante que este valor se gestione correctamente para que los controles de volumen de sonido de interfaz funcionen correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. Además, esta función utiliza la función NormalizeVolumeToDb para convertir el valor de porcentaje a decibelios antes de aplicarlo al sistema de audio.
References Faeterna.Scripts.Menus.OptionsMenu.NormalizeVolumeToDb.
Referenced by Faeterna.Scripts.Menus.OptionsMenu._Ready.
void Faeterna.Scripts.Menus.OptionsMenu.OnSpinBoxMasterValueChanged(float value)
Se llama cuando se cambia el valor del control de volumen maestro (slider o spinbox).
Aplica el nuevo valor de volumen maestro al sistema de audio del juego en tiempo real. Permite al jugador ajustar el nivel general de volumen que afecta a todos los sonidos del juego. Este método se llama tanto desde el slider como desde el spinbox para asegurarse de que ambos controles estén sincronizados y reflejen el mismo valor. Es importante que esta función esté correctamente implementada para que los controles de volumen maestro funcionen correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. Además, esta función utiliza la función NormalizeVolumeToDb para convertir el valor de porcentaje a decibelios antes de aplicarlo al sistema de audio. value Nuevo valor de volumen maestro en porcentaje (0-100) seleccionado por el jugador a través del slider o spinbox. Este valor se utiliza para actualizar el nivel de volumen maestro en el sistema de audio del juego en tiempo real, permitiendo al jugador ajustar el volumen general del juego según sus preferencias. Es importante que este valor se gestione correctamente para que los controles de volumen maestro funcionen correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. Además, esta función utiliza la función NormalizeVolumeToDb para convertir el valor de porcentaje a decibelios antes de aplicarlo al sistema de audio.
References Faeterna.Scripts.Menus.OptionsMenu.NormalizeVolumeToDb.
void Faeterna.Scripts.Menus.OptionsMenu.OnSpinBoxMusicValueChanged(float value)
Se llama cuando se cambia el valor del control de volumen de música (slider o spinbox).
Aplica el nuevo valor de volumen de música al sistema de audio del juego en tiempo real. Permite al jugador ajustar el nivel de volumen específico para la música, lo que afecta a las pistas musicales del juego. Este método se llama tanto desde el slider como desde el spinbox para asegurarse de que ambos controles estén sincronizados y reflejen el mismo valor. Es importante que esta función esté correctamente implementada para que los controles de volumen de música funcionen correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. Además, esta función utiliza la función NormalizeVolumeToDb para convertir el valor de porcentaje a decibelios antes de aplicarlo al sistema de audio. value Nuevo valor de volumen de música en porcentaje (0-100) seleccionado por el jugador a través del slider o spinbox. Este valor se utiliza para actualizar el nivel de volumen de la música en el sistema de audio del juego en tiempo real, permitiendo al jugador ajustar el volumen específico para las pistas musicales del juego según sus preferencias. Es importante que este valor se gestione correctamente para que los controles de volumen de música funcionen correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. Además, esta función utiliza la función NormalizeVolumeToDb para convertir el valor de porcentaje a decibelios antes de aplicarlo al sistema de audio.
References Faeterna.Scripts.Menus.OptionsMenu.NormalizeVolumeToDb.
void Faeterna.Scripts.Menus.OptionsMenu.OnSpinBoxSoundFXValueChanged(float value)
Se llama cuando se cambia el valor del control de volumen de efectos de sonido (slider o spinbox).
Aplica el nuevo valor de volumen de efectos de sonido al sistema de audio del juego en tiempo real. Permite al jugador ajustar el nivel de volumen específico para los efectos de sonido, lo que afecta a los sonidos relacionados con acciones, interacciones y eventos en el juego. Este método se llama tanto desde el slider como desde el spinbox para asegurarse de que ambos controles estén sincronizados y reflejen el mismo valor. Es importante que esta función esté correctamente implementada para que los controles de volumen de efectos de sonido funcionen correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. Además, esta función utiliza la función NormalizeVolumeToDb para convertir el valor de porcentaje a decibelios antes de aplicarlo al sistema de audio. value Nuevo valor de volumen de efectos de sonido en porcentaje (0-100) seleccionado por el jugador a través del slider o spinbox. Este valor se utiliza para actualizar el nivel de volumen de los efectos de sonido en el sistema de audio del juego en tiempo real, permitiendo al jugador ajustar el volumen específico para los sonidos relacionados con acciones, interacciones y eventos en el juego según sus preferencias. Es importante que este valor se gestione correctamente para que los controles de volumen de efectos de sonido funcionen correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. Además, esta función utiliza la función NormalizeVolumeToDb para convertir el valor de porcentaje a decibelios antes de aplicarlo al sistema de audio.
References Faeterna.Scripts.Menus.OptionsMenu.NormalizeVolumeToDb.
void Faeterna.Scripts.Menus.OptionsMenu.OnSpinBoxEnviromentValueChanged(float value)
Se llama cuando se cambia el valor del control de volumen de ambiente (slider o spinbox).
Aplica el nuevo valor de volumen de ambiente al sistema de audio del juego en tiempo real. Permite al jugador ajustar el nivel de volumen específico para los sonidos ambientales, lo que afecta a los sonidos relacionados con el entorno del juego, como el viento, la lluvia, los animales, etc. Este método se llama tanto desde el slider como desde el spinbox para asegurarse de que ambos controles estén sincronizados y reflejen el mismo valor. Es importante que esta función esté correctamente implementada para que los controles de volumen de ambiente value Nuevo valor de volumen de ambiente en porcentaje (0-100) seleccionado por el jugador a través del slider o spinbox. Este valor se utiliza para actualizar el nivel de volumen de los sonidos ambientales en el sistema de audio del juego en tiempo real, permitiendo al jugador ajustar el volumen específico para los sonidos relacionados con el entorno del juego según sus preferencias. Es importante que este valor se gestione correctamente para que los controles de volumen de ambiente funcionen correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. Además, esta función utiliza la función NormalizeVolumeToDb para convertir el valor de porcentaje a decibelios antes de aplicarlo al sistema de audio.
References Faeterna.Scripts.Menus.OptionsMenu.NormalizeVolumeToDb.
void Faeterna.Scripts.Menus.OptionsMenu.OnSpinBoxUISoundValueChanged(float value)
Se llama cuando se cambia el valor del control de volumen de sonido de interfaz (slider o spinbox).
Aplica el nuevo valor de volumen de sonido de interfaz al sistema de audio del juego en tiempo real. Permite al jugador ajustar el nivel de volumen específico para los sonidos relacionados con la interfaz del juego, como los clics, las notificaciones, los menús, etc. Este método se llama tanto desde el slider como desde el spinbox para asegurarse de que ambos controles estén sincronizados y reflejen el mismo valor. Es importante que esta función esté correctamente implementada para que los controles de volumen de sonido de interfaz funcionen correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. Además, esta función utiliza la función NormalizeVolumeToDb para convertir el valor de porcentaje a decibelios antes de aplicarlo al sistema de audio. value Nuevo valor de volumen de sonido de interfaz en porcentaje (0-100) seleccionado por el jugador a través del slider o spinbox. Este valor se utiliza para actualizar el nivel de volumen de los sonidos relacionados con la interfaz del juego en el sistema de audio del juego en tiempo real, permitiendo al jugador ajustar el volumen específico para los sonidos de la interfaz según sus preferencias. Es importante que este valor se gestione correctamente para que los controles de volumen de sonido de interfaz funcionen correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. Además, esta función utiliza la función NormalizeVolumeToDb para convertir el valor de porcentaje a decibelios antes de aplicarlo al sistema de audio.
References Faeterna.Scripts.Menus.OptionsMenu.NormalizeVolumeToDb.
void Faeterna.Scripts.Menus.OptionsMenu.OnSavePressed()
Se llama cuando se presiona el botón de guardar en el menú de opciones.
Aplica todas las configuraciones seleccionadas por el jugador y las guarda utilizando la clase SaveSettings. Esto incluye configuraciones gráficas como antialiasing, VSync, resolución, bloqueo de FPS, calidad de sombras, así como configuraciones de audio como volumen maestro, música, efectos de sonido, ambiente y sonido de interfaz. Al presionar el botón de guardar, se reproduce una animación de presión para proporcionar retroalimentación visual al jugador, y luego se llama al método SaveOptions de la clase SaveSettings para almacenar todas las configuraciones seleccionadas. Es importante que esta función esté correctamente implementada para que las configuraciones seleccionadas por el jugador se apliquen correctamente al juego y se guarden para futuras sesiones.
References Faeterna.Scripts.Menus.OptionsMenu._antialiasing, Faeterna.Scripts.Menus.OptionsMenu._enviroment, Faeterna.Scripts.Menus.OptionsMenu._fpslock, Faeterna.Scripts.Menus.OptionsMenu._fpsValue, Faeterna.Scripts.Menus.OptionsMenu._master, Faeterna.Scripts.Menus.OptionsMenu._music, Faeterna.Scripts.Menus.OptionsMenu._saveButton, Faeterna.Scripts.Menus.OptionsMenu._saveSettings, Faeterna.Scripts.Menus.OptionsMenu._screen, Faeterna.Scripts.Menus.OptionsMenu._shadows, Faeterna.Scripts.Menus.OptionsMenu._soundfx, Faeterna.Scripts.Menus.OptionsMenu._uisound, Faeterna.Scripts.Menus.OptionsMenu._vsync, Faeterna.Scripts.Tools.ButtonTools.PlayPressAnimation.
void Faeterna.Scripts.Menus.OptionsMenu.OnExitPressed()
Se llama cuando se presiona el botón de salir en el menú de opciones.
Cierra el menú de opciones y vuelve al menú principal. Al presionar el botón de salir, se reproduce una animación de presión para proporcionar retroalimentación visual al jugador, y luego se establece la propiedad Visible del menú de opciones en false para ocultarlo. Es importante que esta función esté correctamente implementada para que el menú de opciones se cierre correctamente y para que el jugador pueda volver al menú principal sin problemas.
References Faeterna.Scripts.Menus.OptionsMenu._exitButton, Faeterna.Scripts.Tools.ButtonTools.PlayPressAnimation.
static void Faeterna.Scripts.Menus.OptionsMenu.ApplyShadowQuality(RenderingServer.ShadowQuality quality)
Aplica la configuración de calidad de sombras seleccionada al juego en tiempo real.
Permite al jugador elegir entre diferentes niveles de calidad de sombras para mejorar la apariencia visual del juego según sus preferencias. Al seleccionar una opción, se actualiza la configuración de calidad de sombras del juego para reflejar esa elección. Es importante que esta función esté correctamente implementada para que el control de calidad de sombras funcione correctamente en el menú de opciones y para que los cambios se apliquen en tiempo real al juego. Además, esta función maneja posibles excepciones al aplicar la configuración de sombras, especialmente en entornos sin backend gráfico, para garantizar que el juego no se bloquee y que se informe adecuadamente al jugador si no se pueden aplicar las configuraciones seleccionadas. quality Configuración de calidad de sombras seleccionada por el jugador. Este parámetro se utiliza para determinar qué nivel de calidad de sombras aplicar al juego. Cada nivel de calidad de sombras corresponde a una configuración específica que afecta la apariencia visual de las sombras en el juego. Es importante que esta función maneje posibles excepciones al aplicar la configuración de sombras, especialmente en entornos sin backend gráfico, para garantizar que el juego no se bloquee y que se informe adecuadamente al jugador si no se pueden aplicar las configuraciones seleccionadas.
Referenced by Faeterna.Scripts.Menus.OptionsMenu.OnOptionShadowButtonItemSelected.
float Faeterna.Scripts.Menus.OptionsMenu.NormalizeVolumeToDb(float percentValue)
Normaliza un valor de volumen dado en porcentaje (0-100) a decibelios (dB) para su uso con el sistema de audio del juego.
El sistema de audio generalmente utiliza decibelios para representar los niveles de volumen, donde 0 dB es el nivel máximo y valores negativos representan niveles más bajos. Esta función convierte un valor de porcentaje a un valor de decibelios utilizando una fórmula que asegura que un valor de 0% corresponda a -80 dB (silencio) y un valor de 100% corresponda a 0 dB (volumen máximo). Es importante que esta función esté correctamente implementada para que los controles de volumen en el menú de opciones funcionen correctamente y para que los cambios en el volumen se apliquen percentValue Valor de volumen en porcentaje (0-100) que se desea convertir a decibelios. Este valor se utiliza para calcular el nivel de volumen en decibelios que se aplicará al sistema de audio del juego. Es importante que este valor esté dentro del rango de 0 a 100 para que la función funcione correctamente y para que los cambios en el volumen se apliquen de manera adecuada al juego. Valor de volumen en decibelios (dB) correspondiente al valor de porcentaje dado. Un valor de 0% corresponde a -80 dB (silencio) y un valor de 100% corresponde a 0 dB (volumen máximo). Este valor se utiliza para configurar el nivel de volumen en el sistema de audio del juego, permitiendo que los cambios realizados por el jugador en el menú de opciones se reflejen correctamente en el audio del juego. Es importante que este valor se calcule correctamente para que los controles de volumen funcionen adecuadamente en el menú de opciones.
Referenced by Faeterna.Scripts.Menus.OptionsMenu.OnHEnviromentSliderValueChanged, Faeterna.Scripts.Menus.OptionsMenu.OnHMasterSliderValueChanged, Faeterna.Scripts.Menus.OptionsMenu.OnHMusicSliderValueChanged, Faeterna.Scripts.Menus.OptionsMenu.OnHSoundFXSliderValueChanged, Faeterna.Scripts.Menus.OptionsMenu.OnHUISoundSliderValueChanged, Faeterna.Scripts.Menus.OptionsMenu.OnSpinBoxEnviromentValueChanged, Faeterna.Scripts.Menus.OptionsMenu.OnSpinBoxMasterValueChanged, Faeterna.Scripts.Menus.OptionsMenu.OnSpinBoxMusicValueChanged, Faeterna.Scripts.Menus.OptionsMenu.OnSpinBoxSoundFXValueChanged, Faeterna.Scripts.Menus.OptionsMenu.OnSpinBoxUISoundValueChanged.