Faeterna::Scripts::Personaje::LiraAnimationTree
Lira Faeterna.Scripts.Personaje.LiraAnimationTree._lira
AnimationTree Faeterna.Scripts.Personaje.LiraAnimationTree._animTree
AnimationNodeStateMachinePlayback Faeterna.Scripts.Personaje.LiraAnimationTree._stateMachine
const string Faeterna.Scripts.Personaje.LiraAnimationTree.StateIdle
const string Faeterna.Scripts.Personaje.LiraAnimationTree.StateRun
const string Faeterna.Scripts.Personaje.LiraAnimationTree.StateJump
const string Faeterna.Scripts.Personaje.LiraAnimationTree.StateFall
const string Faeterna.Scripts.Personaje.LiraAnimationTree.StateDash
const string Faeterna.Scripts.Personaje.LiraAnimationTree.StateAim
const string Faeterna.Scripts.Personaje.LiraAnimationTree.StateShot
const string Faeterna.Scripts.Personaje.LiraAnimationTree.StateKick
const string Faeterna.Scripts.Personaje.LiraAnimationTree.StateGetHit
const string Faeterna.Scripts.Personaje.LiraAnimationTree.ParamPlayback
const string Faeterna.Scripts.Personaje.LiraAnimationTree.ParamKickRequest
const string Faeterna.Scripts.Personaje.LiraAnimationTree.ParamKickActive
override void Faeterna.Scripts.Personaje.LiraAnimationTree._Ready()
void Faeterna.Scripts.Personaje.LiraAnimationTree.Travel(string stateName)
Transiciona suavemente al estado indicado.
Referenced by Faeterna.Scripts.Personaje.LiraAnimationTree.IsKicking.
void Faeterna.Scripts.Personaje.LiraAnimationTree.Start(string stateName)
Salta directamente al estado sin blend (útil para interrupciones).
Referenced by Faeterna.Scripts.Personaje.LiraAnimationTree.OnAnimationFinished, Faeterna.Scripts.Personaje.LiraAnimationTree.PlayKick.
string Faeterna.Scripts.Personaje.LiraAnimationTree.CurrentState()
Devuelve el nombre del estado actual del StateMachine.
Referenced by Faeterna.Scripts.Personaje.LiraAnimationTree.IsKicking, Faeterna.Scripts.Personaje.LiraAnimationTree.OnAnimationFinished.
void Faeterna.Scripts.Personaje.LiraAnimationTree.PlayIdle()
void Faeterna.Scripts.Personaje.LiraAnimationTree.PlayRun()
void Faeterna.Scripts.Personaje.LiraAnimationTree.PlayJump()
void Faeterna.Scripts.Personaje.LiraAnimationTree.PlayFall()
void Faeterna.Scripts.Personaje.LiraAnimationTree.PlayDash()
void Faeterna.Scripts.Personaje.LiraAnimationTree.PlayAim()
void Faeterna.Scripts.Personaje.LiraAnimationTree.PlayShot()
void Faeterna.Scripts.Personaje.LiraAnimationTree.PlayGetHit()
void Faeterna.Scripts.Personaje.LiraAnimationTree.PlayKick()
Lanza la animación de kick.
Si el StateMachine tiene un nodo OneShot llamado "kick_shot", lo dispara para superponerlo sobre el estado base. De lo contrario, viaja al estado "kick".
References Faeterna.Scripts.Personaje.LiraAnimationTree.Start.
bool Faeterna.Scripts.Personaje.LiraAnimationTree.IsKicking()
¿Está activa la animación de kick (OneShot)?
References Faeterna.Scripts.Personaje.LiraAnimationTree.CurrentState, Faeterna.Scripts.Personaje.LiraAnimationTree.Travel.
override void Faeterna.Scripts.Personaje.LiraAnimationTree._Process(double delta)
void Faeterna.Scripts.Personaje.LiraAnimationTree.AimReleased()
Llama a este método cuando el jugador suelta el botón de aim.
Reproduce aim al revés y luego vuelve a idle.
void Faeterna.Scripts.Personaje.LiraAnimationTree.OnAnimationFinished()
Cuando termina una animación de un solo ciclo (kick, shot, getHit), volvemos al estado base.
References Faeterna.Scripts.Personaje.LiraAnimationTree.CurrentState, Faeterna.Scripts.Personaje.LiraAnimationTree.Start.